### PR TITLE
ini update

### PR DESCRIPTION
**Pull request by purplemarshmallow**

### CODE REVIEW

**Comment by Predator82Germany** [comment]
I have a ROM called Pokemon Stadium 2 (J) which is named Pocket Monsters Stadium 2 on title screen with POKEMON STADIUM 2 as intern name

**Comment by purplemarshmallow** [comment]
Pokemon Stadium 2 (J) is a different game
Pokemon Stadium 2 (J) is just named Pokemon Stadium in different regions

**Comment by gonetz** [comment]
@purplemarshmallow  - changes merged

@Predator82Germany I can't merge your changes. It seem you made them for a wrong branch. Please update your repository and cherepick your commit over @purplemarshmallow  changes

**Comment by gonetz** [comment]
Stop! purplemarshmallow 's commit alrready contains all necessary changes

**Comment by gonetz** [comment]
So many threads for one issue!

**Comment by Predator82Germany** [comment]
Better so before there are to many wrong things

**Pull request merged**
