### PR TITLE
Fix OpenGL ES 3.0 build in Nexus 6p

### PR DESCRIPTION
**Pull request by fzurita**
This fixes issues with Nexus 6p in OpengGL ES 3.0 mode. It doesn't fix OpenGL ES 2.0 or 3.1. I suspect OpenGL ES 2.0 is the same fix. I'm still not sure what is wrong with the 3.1 version.

The fix is basically to not declare functions that are not defined later on in the GLSL.

Partial fix for this:

https://github.com/gonetz/GLideN64/issues/895

### CODE REVIEW

**Comment by gonetz** [comment]
What about this commit:
https://github.com/mupen64plus-ae/mupen64plus-ae/commit/db87ffdf77a1029e0437cfd7ffaf3e507c33cba2

Is it unnecessary?

**Comment by fzurita** [comment]
No, I took that out, it didn't make a difference.

**Comment by gonetz** [comment]
Added:
https://github.com/gonetz/GLideN64/commit/25d9ae1fb85279e57d16129b5aadf3855bf727a6

I've corrected your code a bit to make it compliant with project's code style.

**Comment by fzurita** [comment]
Cool, thanks

**Comment by gonetz** [comment]
Thank you! I'm getting not so many useful code fixes. It's great to get help :)

**Pull request closed without merging**
