### PR TITLE
Pandora support

### PR DESCRIPTION
**Pull request by ptitSeb**
Support for Pandora (GLES2 on Linux)

### CODE REVIEW

**Comment by gonetz** [comment]
I don't understand your change for TextureFilters_xbrz.cpp. Why you just disable part of code?

**Comment by ptitSeb** [comment]
Ah yes, I had to, it doesn't compile with GCC 6.0 (or 5.1). I have the same issue with PPSSPP. I haven't found a solution for it.

**Comment by gonetz** [comment]
You just remove part of code for all platforms. Why not
#ifndef PANDORA
?
Or just remove TextureFilters_xbrz.cpp from PANDORA project.

**Comment by ptitSeb** [comment]
Yeah, my mistake, I forgot to put behind #ifdef PANDORA
I'll fix that.

**Comment by gonetz** [comment]
Please remove #if 0 	//PANDORA disable from parent commit.

**Comment by ptitSeb** [comment]
How do I do that ? :(

**Comment by gonetz** [comment]
git checkout 40e412d
make corrections in TextureFilters_xbrz.cpp
git add TextureFilters_xbrz.cpp
git commit --amend
git cherry-pick b3ace08

**Comment by gonetz** [comment]
Want me to do it for you?

**Comment by ptitSeb** [comment]
I'm trying thanks for the help :)

**Comment by ptitSeb** [comment]
How to push the changes? I'm still in a detached HEAD.

**Comment by gonetz** [comment]
git checkout HEAD -b ptitSeb-master
git push ptitSeb-master
something like this

**Pull request closed without merging**
