### PR TITLE
Fix CBFD lighting in Android

### PR DESCRIPTION
**Pull request by fzurita**
This fixes CBFD lighting in Android. It looks a lot more correct now.

### CODE REVIEW

**Comment by AmbientMalice** [comment]
Is the lighting correct-ish in the PC version before this?

**Comment by fzurita** [comment]
I'm not sure, it was definitely not correct in android. I haven't tried the PC version.

**Comment by fzurita** [comment]
I have compared this while running in LLE mode, and to be truthful, it's not close to that. But this gets rid of some very annoying random flickering in Android.

**Comment by fzurita** [comment]
By the way, the reason why I made this change is because often omg of the lights always had all fields zeroed out. Trying to apply these lights cause the conker model to be fully lot momentarily.

One thing I'm noticing is that we often have negative intensity for lights. I see that we have checks for that, but the game must be generating those lights for a reason. Should really be ignoring them?

**Comment by weinerschnitzel** [comment]
Hey could you post screenshots of your progress, experiments, discoveries, and comparisons in CBFD lighting? 

Using the negative values for something sounds like a good lead.

Are there any cheat codes that can disable some lighting to make it easier to confirm how point lighting works?

**Comment by fzurita** [comment]
The effects are hard to capture with screenshots. A video would be better suited, but I'm I'll equipped for that. Too much setup.

I have the feeling that when the point lights are zeroed out, that we are instead supposed to use one of the non-point lights to replace it with.

The reason I think this, is because when running in LLE mode, when we would normally get this zeroed out lights, at these points in time Conker's model lighting matches the background lighting.

**Comment by Frank-74** [comment]
By your reasoning above, Conker's model lighting should allways use the background lighting when point lights are zeroed.

A video or screenshot from a real N64 is needed to see how it's supposed to look.

**Comment by fzurita** [comment]
Angrylion shows the effect correctly I believe as well. It's very hard to find footage of a real N64 in YouTube.

**Comment by gonetz** [comment]
At which points of the game the lighting looks a lot more correct now?

**Comment by fzurita** [comment]
I have not played the whole game but intro scene in the throne and in-game. Without this fix, Conker's lighting keeps flickering to full brightness over and over. With this fix, his lighting stays consistent.

Either way, I don't think we should be applying a light with all fields zeroed out.

**Comment by gonetz** [comment]
I tested this fix a bit and did not notice much difference. At least it does not break anything, so merged: b81fb2336

**Comment by fzurita** [comment]
Did you try with Android?

**Comment by gonetz** [comment]
Not yet

**Comment by fzurita** [comment]
Ok. I thought that you may have been using project 64 and the behavior may not have been the same there.

**Pull request closed without merging**
