### PR TITLE
Allow clang build to work in Android.

### PR DESCRIPTION
**Pull request by fzurita**
This doesn't fix 3DMathNeon.

### CODE REVIEW

**Comment by fzurita** [comment]
I just tried to build the newest master with clang and it's not building, so probably more fixes incoming.

**Comment by gonetz** [comment]
Ok. Can I help?

**Comment by gonetz** [comment]
I see error in Textures.cpp. I'll fix it. VS compiler also can't compile that code.

**Comment by gonetz** [comment]
Fixed: bfe5b6078e7

**Comment by gonetz** [comment]
I tested clang build on Note3. Frame buffer effects do not work, plugin crashed on exit.

**Comment by fzurita** [comment]
Interesting, I didn't have that problem. Maybe there's is some underlying bug in the code that the clang compiler is exposing.

**Comment by gonetz** [comment]
I wish soonest recovery for your family. All my family also were sick with the flu this winter. It was nasty. Anti-cough syrup was consumed by liters.

**Comment by fzurita** [comment]
Thanks!

**Comment by fzurita** [comment]
So this file name is too long for some reason: opengl_ColorBufferReaderWithBufferStorage.h/cpp. It doesn't compile with clang unless I reduce it by a few characters.

**Comment by gonetz** [comment]
Windows limitation I guess.

**Comment by fzurita** [comment]
I made a pull request to address it and another easy fix. 3DMathNeon fix should be coming soon.

**Comment by gonetz** [comment]
@fzurita I can be wrong, but  I suppose you need to exclude neon asm code from the project for clang build because assembler inlines contradict with clang way of code generation.

**Comment by fzurita** [comment]
Possibly, I want to try to convince myself of that first.

**Comment by fzurita** [comment]
Also, we should probably bump ShaderStorageFormatVersion. It's still the same version as before the refactor which may hide issues if they are present.

**Comment by gonetz** [comment]
clang works atop of LLVM. Ready asm code will prevent LLVM from doing its optimizations. At least I'd first try to build without neon asm and see how it works.

I'll bump ShaderStorageFormatVersion.

**Comment by fzurita** [comment]
I'm running the latest master with clang. Everything seems to work ok so far. I'm not sure what issues you were running into. Try building my latest version: https://github.com/mupen64plus-ae/mupen64plus-ae

Also, the issue with corrupt lighting when HW Lighting was enabled is now gone.

**Comment by fzurita** [comment]
Conker's bad fur day is in pretty bad shape. Getting into the water in the starting area causes severe slow downs that are not present before the refactor.

**Comment by gonetz** [comment]
> Try building my latest version

The latest version works ok. At least it does not crash.

**Pull request merged**
