### PR TITLE
Fixing what is almost certainly a memory leak

### PR DESCRIPTION
**Pull request by matthewharvey**
I've looked through it again since commit and this is most definitely leaking.

I know we've discussed before that this is not the correct way to be doing this, but for right now we should at least close the leak.

### CODE REVIEW

**Comment by gonetz** [comment]
> I've looked through it again since commit and this is most definitely leaking.

malloc without free. Yes, it is a leak.

>I  know we've discussed before that this is not the correct way to be doing this

I don't remember it. Why freeing memory is not the correct way to be doing this ?

**Comment by gonetz** [comment]
Added, thanks!

**Comment by matthewharvey** [comment]
I wasn't sure if the memory wasn't freed elsewhere, but after doing a thorough check it isn't

Back when I was doing texture work, we both agreed that a more C++ style memory management should be the answer. This will do for now though.

**Comment by gonetz** [comment]
Can you check for memory errors with valgrind? Background textures can be checked with Starcraft. That games uses BG command for almost all graphics.

**Pull request closed without merging**
