### PR TITLE
Update xxHash to v0.7.0

### PR DESCRIPTION
**Pull request by rez-**
This PR updates the xxHash library to version 0.7.0.

Note that I removed the experimental XXH3 library. It looks very promising though!

Herewith a copy-paste of the release notes:

> The main highlight of this release is the introduction of XXH3, a new hash algorithm offering much improved speed, for both large and small inputs.
> 
> XXH3 is still labelled experimental, and must be unlocked with macro XXH_STATIC_LINKING_ONLY. The source code is located into its own xxh3.h file, which is automatically included (and therefore required) by xxhash.c. It's also possible to include xxh3.h directly, which will have a similar effect as triggering XXH_INLINE_ALL.
> At this stage, XXH3 is suitable for ephemeral data and tests, but avoid storing long term hash values yet.
> XXH3 will be transferred into stable in a future release, after a period dedicated to gather users' feedback.
> 
> For more details on XXH3 performance, see [this article](https://fastcompression.blogspot.com/2019/03/presenting-xxh3.html).

from: https://github.com/Cyan4973/xxHash/releases/tag/v0.7.0

### CODE REVIEW

**Comment by gonetz** [comment]
AppVeyor reports that 32bit build failed

**Comment by rez-** [comment]
Everything is fine with the latest commit in the xxHash repo.

I can update the files to the latest development version, or we can use git submodule to include the whole xxHash repo with the latest commit. Or we can wait for the next release.

**Comment by rez-** [comment]
Perhaps my PR should be more about the new hashing algorithm XXH3, but I dont know if it is useful for GLideN64.

**Comment by gonetz** [comment]
> I can update the files to the latest development version

It sounds best for me. I don't want to use git submodule for that task.

**Pull request closed without merging**
