### PR TITLE
UI: Fullscreen resolution list displays aspect ratio

### PR DESCRIPTION
**Pull request by Aquatakat**
This is a feature requested a long time ago by @oddMLan. I'll let you decide if it's a good addition or not.

image

### CODE REVIEW

**Comment by gonetz** [comment]
Looks nice, thanks!
Merged: a4d0796e737

**Comment by Aquatakat** [comment]
@gonetz She also suggested a while ago turning the windowed drop down list into a combo box where one could simply type the resolution if they don't see the one they want in the list. I'm comfortable enough with the code and Qt to make that work if you think it's not a bad idea.

**Comment by oddMLan** [comment]
>She

I'm a cis dude though :)
(not that I mind , I understand the confusion due to my name). But Kimberly is also a name given to males.

**Comment by Aquatakat** [comment]
Whoops, sorry. I've never seen Kimberly as a male name, but there's always a big world out there.

**Comment by gonetz** [comment]
Regarding "turning the windowed drop down list into a combo box where one could simply type the resolution if they don't see the one they want in the list" : if it will be more convenient than current solution for custom windowed resolutions, I don't mind.

**Comment by gonetz** [comment]
>But Kimberly is also a name given to males.

Reminds me of Jayne Cobb :)
http://www.imdb.com/character/ch0003807/mediaviewer/rm650156288

**Comment by Aquatakat** [comment]
A show to watch again.

**Pull request closed without merging**
