### PR TITLE
disable AA in Factor 5 games #249

### PR DESCRIPTION
**Pull request by purplemarshmallow**

### CODE REVIEW

**Comment by theboy181** [comment]
This is not a solution to simple turn off AA. These games look horrible without AA imo.

**Comment by purplemarshmallow** [comment]
Yes it is not a solution
But I think AA should be disabled until this is fixed
#244 same here

**Comment by purplemarshmallow** [comment]
But I noticed it also affects Conker's BFD
there are so many games where AA does not work
add conker?

**Comment by mudlord** [comment]
Thats not a valid solution.
The valid solution is fixed AA.

**Comment by gonetz** [comment]
#244

**Pull request closed without merging**
