### PR TITLE
Optional fragment based writing of depth

### PR DESCRIPTION
**Pull request by fzurita**
Optional writing of gl_Fragdepth. This is to address this issue:

https://github.com/gonetz/GLideN64/issues/1072

Please make sure it works in windows. It's hard to verify that.

### CODE REVIEW

**Comment by fzurita** [comment]
Whoops, I just realized that this has a conflict. I'll rebase it and fix the conflict.

**Comment by fzurita** [comment]
Done

**Comment by gonetz** [comment]
Merged: 74b21d712c
I made several minor fixes in your code.

**Comment by fzurita** [comment]
Ok, thanks. What are they so I don't make that mistake again?

**Comment by fzurita** [comment]
Actually, I'll do a diff to figure out what you changed.

**Comment by fzurita** [comment]
Ok, I see what you did. It makes sense, more common code consolidation. And fixed naming on some config parameters.

**Comment by gonetz** [comment]
yes

**Pull request closed without merging**
