### PR TITLE
Port GLN64 for Android NEON optimizations

### PR DESCRIPTION
**Pull request by fzurita**
These optimizations provide a small performance boost in Android. They can also be potentially used in the Raspberry Pi with the right CMake changes.

See this issue: https://github.com/gonetz/GLideN64/issues/1037

### CODE REVIEW

**Comment by fzurita** [comment]
Also, I converted leading spaces to tabs in files I modified. This makes it seem like I made more changes than I actually did.

**Comment by fzurita** [comment]
Looks like u broke something, lighting is all messed up in Zelda

**Comment by fzurita** [comment]
After learning enough assembly to figure out what was happening, I was able to come up with a fix. O updated the pull request.

**Comment by fzurita** [comment]
Here is the updated Android makefile if you want to try this out:

[mupen64plus-video-gliden64.zip](https://github.com/gonetz/GLideN64/files/340629/mupen64plus-video-gliden64.zip)

**Comment by gonetz** [comment]
I don't like bunch of new asm code in gSP.cpp
Please move it to another file.

**Comment by fzurita** [comment]
Ok

**Comment by fzurita** [comment]
I updated the pull request. retrobenny's issues were cleared by not using the shader cache. We need to do something about to prevent the different OpenGL/GLES versions sharing shader cache.

**Comment by fzurita** [comment]
@gonetz is there anything that I need to do that is holding this up?

**Comment by gonetz** [comment]
I was busy with other things and had no time to check your commit, sorry. I want to build it and test on my devices. BTW, do you have a mupen64plus-ae branch with your Neon fixes?

**Comment by fzurita** [comment]
Sorry, I don't mean to make you feel rushed. Take your time, as long as you are not waiting on me.

Yeah, right here is a branch with the changes: https://github.com/mupen64plus-ae/mupen64plus-ae/commits/neon_test

**Comment by gonetz** [comment]
I have built neon_test branch. Zelda MM screenshot from my device:
screenshot_2016-07-05-16-45-57

**Comment by retrobenny** [comment]
You have been met with a terrible fate.

I wonder what is happening exactly this time? Glad to see something after a handful of slow days.

**Comment by fzurita** [comment]
Ok, thanks for testing that. It looks like one of the functions didn't port over correctly. I just have to figure out which it is and fix it. 

Can you by any chance give me a save state?

**Comment by fzurita** [comment]
It's also possible that GLN64 has a buggy lighting function. Did you have to make any mayor changes to GLN64 for Zelda MM lighting to work correctly?

I guess once I narrow down which function is broken, it will be easy to tell.

**Comment by gonetz** [comment]
Autosave  for Zelda MM (U)

https://drive.google.com/open?
id=0B0YqMPjGo3B2clVzQW1ReWNnTGc

**Comment by gonetz** [comment]
Zelda MM has different lighting function ind

**Comment by fzurita** [comment]
Also, I need to cleanup my tab spacing as well. I see that it looks off in several places.

**Comment by fzurita** [comment]
After replacing gSPLightVertex4 with the default version instead of the neon version, the lighting looks correct again in Zelda MM. Yet, when I look at the implementations, they look the same. Hmmm.... Any idea why the glN64 version of this function wouldn't work?

**Comment by fzurita** [comment]
The more I look at it, the more I'm convincing myself that gSPLightVertex4NEON is wrong. I'm going to remove this neon function.

**Comment by fzurita** [comment]
Pull request updated. Please try the latest version.

**Comment by gonetz** [comment]
> Any idea why the glN64 version of this function wouldn't work?

Actually, I'm not sure that default implementation of gSPLightVertex4 is correct. I don't use it for desktop builds. When I modified gSPLightVertex I did similar changes in gSPLightVertex4 blindly, without tests.

**Comment by fzurita** [comment]
The default version gSPLightVertex4 seems to give correct lighting in the save state you provided.

**Comment by gonetz** [comment]
Good to know. I'm building updated neon branch.

**Comment by gonetz** [comment]
Works ok. Merged.

**Comment by retrobenny** [comment]
Sorry to bring this back open,but I ran into texture issues after the 2nd run with shader storage on a newer build,it still loses proper textures,so the actual entire issues aren't fixed,only some of them.
This time started with OOT file select missing most of its UI,then on reset,the initial logo had a familiar blue rectangle on it as I have seen in previous builds.

I do have a GS code for now if anyone wants to play it without stutters when shader storage is disabled.
It also uses a required delay fix code to prevent crashing and conveniently makes pausing near instant.
You also need audio synced to make it run at the full framerate,but it shows -1 the normal fps too.

Stutter Stopper
80006463 0004
80006493 0004
D01C7021 0002
801DA5CB 0002
D01C7021 0002
801C7021 0003

**Comment by fzurita** [comment]
This could be related to the texture cache changes.

**Pull request closed without merging**
