### PR TITLE
hack to fix out of buffer write in Donkey Kong 64 (E)

### LINKED ISSUE #355: Donkey Kong 64 (E) crash at start and when loading a new game
Donkey Kong 64 (E) version crash after Rare logo when one of this option is enabled :
- copyDepthToRDRAM
- copyToRDRAM

And it crash when you start a new game when one of this option is enabled : 
- copyDepthToRDRAM
- copyToRDRAM
- detectCFB

My settings to boot DK without crash : 
image

My setting to start a new game without crash : 
image

No problem with (U) version.

### PR DESCRIPTION
**Pull request by purplemarshmallow**
fix #355

### CODE REVIEW

**Comment by AmbientMalice** [comment]
Wouldn't it be ideal to solve GLideN64's framebuffer bugs instead of temp-solving the crashes with hacks? I'm wary that fixes like this are going to backfire.

**Comment by purplemarshmallow** [comment]
I think hacks should only be used if there's no other option. Gonetz came to this conclusion when he investigated this bug:
>It's either bug in game code, or bug in VI emulation on emulator's side. Frame buffer height calculated by the plugin is higher than its real height. Out of buffer write causes crash.

If it's a bug in game code or a bug on emulator's side only a hack can prevent a crash. Frame buffer height is mostly correct in Donkey Kong 64 (E) except for a few cases (after the monkey rap or when loading a game). If frame buffer height is wrong for a short time that's enough to cause a crash. It's easily possible that the missing level of synchronisation from the emulator's side causes these errors. Keep in mind Donkey Kong 64 is known to have timing issues with all emulators.

Everything this hack does is prevent a copy to RDRAM if the values are strange

**Comment by AmbientMalice** [comment]
Vigilante 8 (E) crashes on boot. Likely same issue as DK64 (E). Plus I notice copying framebuffer from RDRAM is broken in a wide range of games. (For example, Mario Tennis crashes. Vigilante 8 crashes. Resident Evil 2 is even more broken.)

**Comment by LegendOfDragoon** [comment]
@AmbientMalice , does the "wobble" occur in Mupen?

**Comment by AmbientMalice** [comment]
@LegendOfDragoon Not exactly. For example, Quake 64 wobbles with PJ64, and "shimmers" with mupen64plus. It's a shifting, phasing effect. Like the colour is being washed out and then bleeding back in.

**Comment by purplemarshmallow** [comment]
I tested Donkey Kong 64 (E) with Jabo's plugin and copy to RDRAM enabled. It does not crash. I wonder if he used a hack or a better formula.

**Comment by gonetz** [comment]
>I wonder if he used a hack or a better formula.
Or hardcoded frame buffer size. IIRC, Jabo's plugin allows user to set frame buffer size manually.

**Comment by purplemarshmallow** [comment]
I'm not sure but I think Jabo's plugin calculates it because it has wrong values as well. But it somehow manages to prevent a crash.
After loading a game there are are two zipper effects. The first one works fine with GLideN64 and Jabo's plugin. The second one is problematic. With GLideN64 my hack prevents a copy to RDRAM, the effect is missing. Without hack there would be a crash. With Jabo's plugin the effect is incorrect, but no crash. Here's a screenshot from Jabo's plugin:
donkey kong 64 e snap0005

**Comment by purplemarshmallow** [comment]
>Jabo's plugin allows user to set frame buffer size manually

Jabo's plugin has "emulated width" and "emulated height" options. I've tested them but they seem to have no impact on copy to RDRAM. Jabo's formulas are very inaccurate, the puzzle effect in Banjo Kazooie (E) is wrong with Jabo's plugin and if you enable copy to RDRAM in Body Harvest (E) the emulator crashes

**Comment by fzurita** [comment]
How about doing this instead at the beginning of the function?

_address = _address & 7F FFFF;

**Comment by purplemarshmallow** [comment]
merge conflict and I'll close for now. I hope there's a better solution

**Pull request closed without merging**
