### PR TITLE
New fb validity check

### PR DESCRIPTION
**Pull request by gonetz**

### CODE REVIEW

**Comment by Predator82Germany** [comment]
[MARIOGOLF64]
Good_Name=Mario Golf (E)(J)(U)
frameBufferEmulation\validityCheckMethod=0

Can´t see differences with all 3 options (may I´m blind then correct me), so use default value?

**Comment by Predator82Germany** [comment]
[THE%20LEGEND%20OF%20ZELDA]
Good_Name=The Legend Of Zelda - Ocarina Of Time (E)(U)(J)
frameBufferEmulation\validityCheckMethod=1

[ZELDA%20MASTER%20QUEST]
Good_Name=The Legend Of Zelda - Ocarina Of Time - Master Quest
frameBufferEmulation\validityCheckMethod=1

Should stay so, is needed to see Link in pause-screen

**Comment by gonetz** [comment]
If a game works with no difference for any validityCheckMethod option, it's better to remove that setting from custom settings for this game at all.

validityCheckMethod=1 for Zelda OOT is essential with no doubt.
Have you checked other games, which had validityCheckMethod = Fill RDRAM with other options?
May be Zelda is the only bad case which need it? It would be great, because Fill RDRAM is dangerous.

I'd like to get results for #410 and #416
@purplemarshmallow, where are you?

**Comment by purplemarshmallow** [comment]
I commented in #416 looks like validityCheckMethod = Fill RDRAM is needed but I think it's safe

**Comment by Predator82Germany** [comment]
Have all tested which have validityCheckMethod in custom.ini while Pokemon

**Comment by purplemarshmallow** [comment]
Fill RDRAM seems to work much better now. I tested #323 but I can't reproduce a crash with the latest build. But it would be risky to use it for every game.

**Comment by purplemarshmallow** [comment]
But fingerprint method works really good. Only 2 games seem to have a problem with it. Zelda OOT and Pokemon Stadium 2. I can't find any other games.

**Comment by baptiste0602** [comment]
@Predator82Germany : For Mario Tennis, Fill RDRAM is useful to fix some shadows.

With fingerprint : 
image

With fillRDRAM : 
image

**Comment by gonetz** [comment]
Let me summarize feedback from this thread and from #416

1. Fill RDRAM is the most reliable method for detection frame buffer validity. purplemarshmallow also found that it's current use does not cause crash in games which crashed before. I guess that this improvement is caused by the fact that I use Fill RDRAM only for auxiliary frame buffers in that version. Main frame buffers are checked using pure Copy RDRAM method, which is safe.
2. Fingerprint gives less reliable result. Again, fingerprint method is used only for auxiliary frame buffers.
3. Plugin still can detect height of auxiliary buffer wrong. Fill RDRAM will cause crash in that case. We don't find such cases, but I can't believe that my code can handle all possible cases. N64 games are very insidious. Fingerprint fills only 2% of buffer area and thus has very little chance to spoil program data in RDRAM.

Conclusion: in fact, I've implemented 2 different methods for validity detection of auxiliary frame buffers: fill and fingerprint. Validity detection for main frame buffers silently uses safe copy method only. Thus, we need only these two methods in GUI. 0 for fingerprint, 1 for fill RDRAM
Since fingerprint is more safe and works fine for most games, I suggest to use it as the default one.
Few games, namely Zelda OOT , Mario Tennis and Pokemon games will get validityCheck=1 (fill) in custom ini. validityCheck option must be removed for other games in custom ini.
That solution will make the project most compatible and safe.

If everyone agree with me, let's finish that work and push it to release level.
I'll correct code and GUI.
@purplemarshmallow, @Predator82Germany and @baptiste0602 : please prepare custom.ini, which I can pull, check and push to release branch.

**Comment by Predator82Germany** [comment]
Pull request done

**Comment by purplemarshmallow** [comment]
Fill RDRAM causes a fatal error with knockout kings 2000
The framenuffer effect still does not work #350

**Comment by gonetz** [comment]
:(

**Comment by Predator82Germany** [comment]
Same crash message like with Donkey Kong 64 (E) #355 & #358

**Comment by gonetz** [comment]
@Predator82Germany - does it crash with any option, or only with Fill RDRAM?

**Comment by Predator82Germany** [comment]
Have all off & only fill on (crash) with fingerprint it works

New bad news: F-Zero X crash after cup select (all regions) with both validity checks

**Comment by gonetz** [comment]
Ok, now we know cases, where Fill does not work. Since Fingerprint is default, it's not a problem.
We may force set it for the games, which crash with Fill option for safety.

**Comment by gonetz** [comment]
I'll check F-Zero

**Comment by gonetz** [comment]
Stupid mistake in my yesterday fixes. Will be fixed and uploaded soon

**Comment by gonetz** [comment]
F-Zero fixed

**Comment by Predator82Germany** [comment]
May we should force all knowed settings to get the best result for users, so they can do nothing wrong if they change settings in gui

**Comment by gonetz** [comment]
Users still able to shot themselves in a leg if they want to: custom ini use is optional.

But the idea is good. What you suggest to add to custom settings?

**Comment by Predator82Germany** [comment]
In this thread
http://gliden64.boards.net/thread/93/gliden64-custom-game-settings
I´ve stored all required settings for most playability til today
When something should forced than this

**Comment by Predator82Germany** [comment]
You´ve send the wrong file?

**Comment by gonetz** [comment]
When?

**Comment by Predator82Germany** [comment]
F-Zero X fix has sam date / time how before

**Comment by gonetz** [comment]
It is not so in my archive. dll file has CRC32=2B773240

**Comment by gonetz** [comment]
Try download again

**Comment by gonetz** [comment]
I downloaded the archive. It is correct.

**Comment by Predator82Germany** [comment]
Have E0A43419

**Comment by purplemarshmallow** [comment]
F-zero x still crashes with f zero x fix
so I think it's the wrong file

**Comment by Predator82Germany** [comment]
lol we should report plugin errors & get download-isues :D

**Comment by gonetz** [comment]
Reuploaded

**Comment by Predator82Germany** [comment]
Works

**Comment by gonetz** [comment]
As expected :)
No idea, what was wrong with previous upload.

**Comment by Predator82Germany** [comment]
May filename
Before Knockout Kings 2000 crash the Rumble-Pack message disappears may its a rumble issue & not fill-fail

**Pull request closed without merging**
