### PR TITLE
Turning GLideN64 into a clone and compile solution part 1

### PR DESCRIPTION
**Pull request by Cetacea3691**
Part 1 of turning GLideN64 into a clone and compile solution.

Added GLideNUI into GLideN64 and configured it to be build when required.
Added dwrite.lib to GLideNUI (a Qt5.6 function requires it).
Added qtpcre.lib to GLideNUI (some Qt5.6 functions require it).
Added ini files into GLideN64 with custom build settings (automatic copy and past).
Added the translation files into GLideNUI with custom build settings (automatic .qm files generation).
Changed GLideN64.dll's output directory (controlled through Global User Macros Control).
Added Global User Macros Control (click on VIEW and then on Other Windows>Property Manager) for final output directory (Release) and Qt directory (QTDIR).
The final output directory (Release) controls ... the final output directory of GLideN64 :D
The Qt directory (QTDIR) controls Qt's installation directory, makes it unnecessary to install the Qt Add-in and will be used for the automatic Qt download and build.

### CODE REVIEW

**Comment by purplemarshmallow** [comment]
You can fork here: https://github.com/octocat/Spoon-Knife

**Comment by Cetacea3691** [comment]
If you're fine with the changes feel free to merge them, then I can get part 2 (automatic Qt downloading and building) ready.

**Comment by gonetz** [comment]
I need time to check it.

How do you plan to do automatic Qt downloading? Also, QT building requires python (and perl?) installed. Will it be installed with QT?

**Comment by purplemarshmallow** [comment]
Unfortunately my bad commit got merged here. @gonetz did a reset @Cetacea3691 you have to do this as well? But I don't know the git command right now.

**Comment by Cetacea3691** [comment]
@purplemarshmallow got it :)

**Comment by gonetz** [comment]
Don't worry. I'll put it to the right place if it does not need to be corrected.

**Comment by Cetacea3691** [comment]
I want to make the automatic Qt download a pre-build event in MSVS and it will require
Git (>= 1.6.x) (for downloading)
Perl (>=5.14) (required for building Qt5.6 from source)
Python (>=2.6.x) (required for building Qt5.6 from source)
I think it's better if we add Git,Perl and Python to GLideN64's wiki page as requirements and let the users download and install them, but if you want I can automate everything.

**Comment by gonetz** [comment]
May be make Perl and Python installation as script options?
If user does not have them already installed, it may ask the script to download and install these tools too.
As I know, it is possible to use Perl and Python binaries without running the installers.

**Comment by Cetacea3691** [comment]
> May be make Perl and Python installation as script options?
If user does not have them already installed, it may ask the script to download and install these tools too.

I want to check if Perl and Python are installed and if they aren't download the zip/portable versions and use them (no installation needed).

**Comment by gonetz** [comment]
I started to check the commits.

<QTDIR>../../../Qt5.6-win32-msvc-static\qtbase</QTDIR>

Do you plan to change project files after each QT version change?
May be it is better to not include version number to the pass?

Also QT5.6 is currently alpha. Let's not use alphas. Stable version is 5.5.1

**Comment by gonetz** [comment]
I put your commit into clone_and_compile branch:
https://github.com/gonetz/GLideN64/tree/clone_and_compile

Please add your next commits here. It will be merged to master when everything will be ready.

**Comment by Cetacea3691** [comment]
I'll remove the Qt version number for now, until I can find a nice way to update the User Macros thru the pre-build event.

I used Qt5.6 because I'm not sure if Qt5.5.1 is fully compatible with MSVS 2015.
What do you think about this idea, I'll test if GLideN64 works with Qt5.5.1 and MSVS 2015 and if it doesn't, I'll add an MSVS version check and use Qt5.6 only for MSVS 2015.

Just to make sure, you want me to make the rest of the pull requests into the clone_and_compile branch?

**Comment by gonetz** [comment]
> What do you think about this idea, I'll test if GLideN64 works with Qt5.5.1 and MSVS 2015 and if it doesn't, I'll add an MSVS version check and use Qt5.6 only for MSVS 2015.

Ok, but check current version first.

> Just to make sure, you want me to make the rest of the pull requests into the clone_and_compile branch?

Yes, I want to have complete solution of the problem in that branch.

**Comment by tony971** [comment]
5.6.0 is stable now so this should be a non-issue.

**Comment by gonetz** [comment]
Obsolete

**Pull request closed without merging**
