### PR TITLE
Get Android building again only for EGL so far.

### PR DESCRIPTION
**Pull request by fzurita**
This relates to https://github.com/gonetz/GLideN64/issues/1335.

This compiles, but there are major graphical issues in the Shield TV.

Unfortunately, there are not GL errors or shader compilation errors that would give me a clue.

### CODE REVIEW

**Comment by fzurita** [comment]
In the gDPFillRectangle logic I refactored, if one replaces:

```
		if (gDP.depthImageAddress == gDP.colorImage.address || gDP.otherMode.cycleType == G_CYC_FILL) {

			frameBufferList().fillRDRAM(ulx, uly, lrx, lry);
			if (config.generalEmulation.enableFragmentDepthWrite == 0 ||
				(ulx == 0 && uly == 0 && lrx == gDP.scissor.lrx && lry == gDP.scissor.lry)) {
				drawer.clearDepthBuffer(ulx, uly, lrx, lry);
				bBufferCleared = true;
			} else {
				depthBufferList().clearBuffer(ulx, uly, lrx, lry);
			}
		}
```

with 

```
		if (gDP.depthImageAddress == gDP.colorImage.address || gDP.otherMode.cycleType == G_CYC_FILL) {

			frameBufferList().fillRDRAM(ulx, uly, lrx, lry);
			drawer.clearDepthBuffer(ulx, uly, lrx, lry);
			bBufferCleared = true;
			
			if (ulx != 0 || uly != 0 || lrx != gDP.scissor.lrx || lry != gDP.scissor.lry) {
				depthBufferList().clearBuffer(ulx, uly, lrx, lry);
			}
		}
```

Pilotwings shadows still seem to work correctly.

**Comment by gonetz** [comment]
I explained situation with depth buffer clear here: https://github.com/gonetz/GLideN64/issues/1335#issuecomment-275917722

I'll merge other fixes.

**Comment by fzurita** [comment]
Yep, I saw. These changes should still be valid.

**Comment by fzurita** [comment]
I commented out the EGLImage code for now. Anything library that uses that code is not compatible with Android 7.0. They disabled access to the private API.

I'm not sure what to do about that yet. I will probably have to do run time loading of the library in the plugin, but only if the Android version allows it.

**Comment by gonetz** [comment]
Do you think that GLES2 devices will get Android 7.0 ?

**Comment by gonetz** [comment]
I merged all your fixes but gDPFillRectangle.

**Comment by fzurita** [comment]
I don't think GLES2 devices will get 7.0.

In the gDPFillRectangle I just refactored the logic so that you didn't have the same code twice. The functionality didn't change.

**Comment by fzurita** [comment]
Also, sorry I made you go through the work of splitting up my commits. You could had asked and I would have done it.

**Comment by gonetz** [comment]
> In the gDPFillRectangle I just refactored the logic so that you didn't have the same code twice. The functionality didn't change.

Nope, you did it wrong. Look, with your code,  if gDP.fillColor.color == DepthClearColor and gDP.otherMode.cycleType == G_CYC_FILL then fillrect saves depth buffer. This condition is always true when fillrect is used for clearing depth buffer. Thus, your code will always call depthBufferList().saveBuffer, which causes useless overheads. My code does not work like this. It takes into account two situation with depth buffer clear:
* gDPSetDepthImage called before fillrect. In that case gDP.depthImageAddress == gDP.colorImage.address, depth buffer already created and set, so depthBufferList().saveBuffer() not called.
* gDPSetDepthImage called after fillrect. In that case gDP.depthImageAddress is not equal to gDP.colorImage.addres yet, but we know that fillrect uses DepthClearColor and cycle mode is FILL. Thus, we are in depth buffer clear situation. We need to call depthBufferList().saveBuffer() to create depth buffer and then clear it.

**Comment by fzurita** [comment]
Ok, I see you are right. And here I thought I was making code simpler. Thanks.

**Comment by fzurita** [comment]
By the way, just adding -DGLESX in addition to -DEGL, makes the GLES 3.1 version work fine. The GLES 3.1 version also break with fragment based depth enabled though. At least in GLES 3.1, I'm getting proper GL errors along with backtraces. A shader seems to be failing to compile. It's a little more difficult to track down where it's happening, but it's a shader being updated by ```_updateStates(DrawingState::Rect);``` in ```GraphicsDrawer::drawRect```

**Comment by fzurita** [comment]
I just fixed the TexrectCopy not compiling.

**Comment by fzurita** [comment]
Ok, now I have bigger issues. We are getting a glError whenever we set  ```uRenderTarget``` using glUniform1i. I'm checking the location of this uniform and it does appear to have a valid location of 1. Not sure what is going on, but it's what is prevent fragment depth write from working.

**Comment by gonetz** [comment]
Program _bad looks like correct fillrect program. uRenderTarget is defined and used, so it's location should be correct. 
I'll try to compile the code myself. I did not build muen64plus-ae for several months. Which tool you use now: Eclipse,  Android Studio?

**Comment by gonetz** [comment]
> gl_FragColor = texture2D(uTex0, vTexCoord0); is not a valid GLSL. gl_FragColor is not built in after GLES 2.0

I added 
#define texture2D  texture
in GLES3 shader header to use the same shader code for GLES2 and newer GL versions. There should not be problem here.

**Comment by fzurita** [comment]
It's not texture2D that is the problem, it's gl_FragColor.

**Comment by fzurita** [comment]
Now we use Android Studio, you should be able to checkout the project and import into Android Studio directly. Just make sure you have the latest SDK/NDK installed.

**Comment by gonetz** [comment]
> It's not texture2D that is the problem, it's gl_FragColor.

Oh, ok.

**Comment by fzurita** [comment]
Gonetz, if you end up trying to get Android Studio to work, let me know if you run into troubles. I should be able to help since I have done it a few times now.

**Comment by gonetz** [comment]
mupen64plus-ae master built successfully just now with Android Studio. At least log says so, I did not try it on a device/emulator. Will it sufficient to replace only gliden64/src folder in jni to build the new code?

**Comment by gonetz** [comment]
I merged your latest fixes.

**Comment by fzurita** [comment]
If you have git-bash, you can run ./pull-gluden64.sh. You can do what you just said. Make sure you do a build->clean after you do that, then after build->"refresh c++ sources"

**Comment by fzurita** [comment]
After you get it running, I would recommend making a new GLideN64 profile then disabling shader storage.

**Comment by fzurita** [comment]
I see that you didn't include 952446ffb349004d89aa081fa4fff4556f327fa8 . Do you see a problem with that change?

**Comment by gonetz** [comment]
> I see that you didn't include 64c3980. Do you see a problem with that change?

I made different fix.

**Comment by fzurita** [comment]
Ok

**Comment by gonetz** [comment]
I can't attach my Shield to PC. Will new code work on GLES3 device?

**Comment by fzurita** [comment]
I have only tried GLES 3.1 device, but in mupen64plus-vide-gliden64.mk, you have to add -DGLESX to LOCAL_CFLAGS towards the bottom.

**Comment by gonetz** [comment]
I copied src from GLideN64 repository to mupen64plus-video-gliden64/src
For every header file, which includes <memory> I got strange error: compiler tries to include android_framework/include/ui/Rect.h:

```
/home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/android_framework/include/ui/GraphicBuffer.h
Information:(25) (Unknown) In file included
/home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/android_framework/include/ui/Rect.h
Error:(50, 17) error: 'numeric_limits' is not a member of 'std'
Error:(50, 49) error: expected primary-expression before '>' token
Error:(50, 50) error: '::max' has not been declared
Information:(50, 50) suggested alternative:
In file included from /home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/memory:62:0,
                 from /home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ContextImpl.h:2,
                 from /home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp:4:
/home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algobase.h:261:5: note:   'std::max'
Error:(53, 17) error: 'numeric_limits' is not a member of 'std'
Error:(53, 49) error: expected primary-expression before '>' token
Error:(53, 50) error: '::max' has not been declared
Information:(53, 50) suggested alternative:
In file included from /home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/memory:62:0,
                 from /home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ContextImpl.h:2,
                 from /home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp:4:
/home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algobase.h:261:5: note:   'std::max'
Error:(55, 17) error: 'numeric_limits' is not a member of 'std'
Error:(55, 49) error: expected primary-expression before '>' token
Error:(55, 50) error: '::max' has not been declared
Information:(55, 50) suggested alternative:
In file included from /home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/memory:62:0,
                 from /home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ContextImpl.h:2,
                 from /home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp:4:
/home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algobase.h:261:5: note:   'std::max'
Error:(58, 17) error: 'numeric_limits' is not a member of 'std'
Error:(58, 49) error: expected primary-expression before '>' token
Error:(58, 50) error: '::max' has not been declared
Information:(58, 50) suggested alternative:
In file included from /home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/memory:62:0,
                 from /home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ContextImpl.h:2,
                 from /home/lipskiy/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp:4:
/home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algobase.h:261:5: note:   'std::max'
Error:(50, 17) error: 'numeric_limits' is not a member of 'std'
Error:(50, 49) error: expected primary-expression before '>' token
Error:(50, 50) error: '::max' has not been declared
Information:(50, 50) note: suggested alternative:
Error:(53, 17) error: 'numeric_limits' is not a member of 'std'
Error:(53, 49) error: expected primary-expression before '>' token
Error:(53, 50) error: '::max' has not been declared
Information:(53, 50) note: suggested alternative:
Error:(55, 17) error: 'numeric_limits' is not a member of 'std'
Error:(55, 49) error: expected primary-expression before '>' token
Error:(55, 50) error: '::max' has not been declared
Information:(55, 50) note: suggested alternative:
Error:(58, 17) error: 'numeric_limits' is not a member of 'std'
Error:(58, 49) error: expected primary-expression before '>' token
Error:(58, 50) error: '::max' has not been declared
Information:(58, 50) note: suggested alternative:
/home/lipskiy/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algobase.h
Information:(261, 5) note:   'std::max'
Information:(261, 5) note:   'std::max'
Information:(261, 5) note:   'std::max'
Information:(261, 5) note:   'std::max'
Information:BUILD FAILED
```

**Comment by gonetz** [comment]
Ok, I built the new code and installed it on my Shield. Lots of glitches with buffers. At least it compiled and run.

**Comment by gonetz** [comment]
I disabled fragment depth option and everything started to work fine. Interesting, what breaks it on Android?

**Comment by gonetz** [comment]
Russian translation for GLideN64 is beyond good and evil someplaces.

**Comment by fzurita** [comment]
Yeah, it was a random person that provided it to me. Since I didn't have it, I added it. You can always give me an updated translation for those settings :)

See my previous posts to see what is breaking in Android.

**Comment by fzurita** [comment]
So I'm trying something new. I disabled all shader caching in ``` CombinerInfo::setCombine(u64 _mux )``` and I'm getting a new error when uRenderTarget fails to be written to. 

```
01-31 00:00:20.690 20566-21043/org.mupen64plusae.v3.alpha I/Adreno: Error: input vNumLights not declared in output from previous stage.
                                                                    Error: Linking failed.
```

**Comment by gonetz** [comment]
> Edit 2: So it seems like we may have two different shader programs with the same mux id....

What is mux id? There must be no shader program with the same CombinerKey.
At the same time, there can be more than one shader program, corresponding to the same gDPCombine.
CombinerKey includes gDPCombine::mux plus additional bits for cycle mode and bit for Rect flag.
If the same gDPCombine::mux used for different cycle modes, different shader programs will be created.

**Comment by fzurita** [comment]
Ok, that makes sense based on what I have seen in your code. It may just be coincidence that they have the same gDPCombine. That has been the only connection I have seen so far with this issue.

**Comment by fzurita** [comment]
@gonetz In glsl_CombinerProgramUniformFactorycpp, the check is 
```
if (_inputs.usesHwLighting())
```

to determine if there are uniforms related to hw lighting. Yet in glsl_CombinerProgramBuilder.cpp, the check is

```combinerInputs.usesShadeColor()```

Which one is right?

**Comment by gonetz** [comment]
Both are right.

CombinerProgramBuilder::buildCombinerProgram works first. Condition for HWLighting is 

```
	const bool bUseHWLight = 
		config.generalEmulation.enableHWLighting != 0 && GBI.isHWLSupported() && combinerInputs.usesShadeColor();

```
if bUseHWLight  is true, it added to combinerInputs:
```
	if (bUseHWLight)
		combinerInputs.addInput(G_GCI_HW_LIGHT);

```

These combinerInputs passed to CombinerProgramUniformFactory::buildUniforms, which can safely use 
`if (_inputs.usesHwLighting())`

**Comment by fzurita** [comment]
@gonetz I edited my comment. See what I added after.

**Comment by gonetz** [comment]
Result of 
```
const bool bUseHWLight = 
		config.generalEmulation.enableHWLighting != 0 && GBI.isHWLSupported() && combinerInputs.usesShadeColor();
```
Is the same for the same mux if config not changed. How we can have two different shaders?

**Comment by fzurita** [comment]
```GBI.isHWLSupported()``` seems to not return the same. For the same mux input.

**Comment by gonetz** [comment]
Hmm, yes. If some game uses S2DEX and F3DEX, that situation is possible.

**Comment by gonetz** [comment]
Which game you tested?

**Comment by fzurita** [comment]
Mario 64.

**Comment by fzurita** [comment]
Either way, fixing this situation by disabling HW lighting in configuration, does not fix the issues that I'm seeing with fragment based depth.

**Comment by gonetz** [comment]
Ops! That must not be. Mario uses only one ucode AFAIK,

**Comment by fzurita** [comment]
I'm seeing this happen though based on the logging I added. ```GBI.isHWLSupported()``` first returns false, then very quickly returns true.

**Comment by gonetz** [comment]
```
if (m_pCurrent == nullptr)
		return false;
```

If ucode is not detected yet, it will return false.

**Comment by fzurita** [comment]
Ok, that must be happening. Is it really correct to return true or false? The right answer is "unknown"

**Comment by gonetz** [comment]
True

**Comment by gonetz** [comment]
I'll fix it later. Let's find, what is wrong with fragment based depth.
You said, that you got GLError, when you set uniform for renderTarget. What kind of error it was?

**Comment by fzurita** [comment]
OpenGL Error: invalid operation (502)

**Comment by gonetz** [comment]
The only reason, which can cause invalid operation for setting this uniform is bad/unset shader program.
You don't get errors from checkShaderCompileStatus and checkProgramLinkStatus, do you?

**Comment by fzurita** [comment]
Nope, no errors there.

**Comment by gonetz** [comment]
Uniform updated only from CombinerProgramImpl::update, which set useProgram.

Please try: 
* disable all caching in opengl_CachedFunctions.h (comment all CACHED_USE_CACHE)
* add opengl::Utils::isGLError(); after m_useProgram->useProgram(m_program); in CombinerProgramImpl::update

**Comment by fzurita** [comment]
Ok, commenting out all the CACHED_USE_CACHE got rid of all the GL errors. There are still graphics errors though.

**Comment by fzurita** [comment]
That gives me a hint to where to look for the GL error. Still need to figure out why all 3d graphics in mario 64 are not being displayed with fragment based depth enabled.

**Comment by gonetz** [comment]
Is there a way to debug cpp code on Android device with Android Studio? I ran 'Debug app, Shifp+F9)', but my breakpoints are ignored.

**Comment by fzurita** [comment]
It's very hit or miss. I have tried it a few times and sometimes it works and sometimes it doesn't. It's only reliable when using java from my experience.

**Comment by gonetz** [comment]
:( I hoped that the situation is changed.

**Comment by gonetz** [comment]
I disabled caching in opengl_CachedFunctions.h
All issues in SM64 gone!

**Comment by fzurita** [comment]
Hmm... interesting. I don't get such a nice result, I still have a black screen.

**Comment by gonetz** [comment]
NVidia Shield

**Comment by fzurita** [comment]
Ok, I'm using my Adreno device right now. Let me try the shield TV.

**Comment by gonetz** [comment]
Some Cached1 function causes problem with buffers on Shield.

**Comment by fzurita** [comment]
I was able to reproduce the problem with the shield again by running the EGL version in GLES 3.2 mode instead. I think this helps narrow it down ever further. It was something we were doing differently with GLESX vs full GL before refactoring that we must be doing the same between the two now.

**Comment by gonetz** [comment]
CacheduseProgram causes issue with shader depth on Shield. If I disable
`if (update(_program))`
line, everything else works.
I'll try to find, what can cause the problem.

**Comment by fzurita** [comment]
ok

**Comment by fzurita** [comment]
So will be back to normal once the cache issue is fixed. GLESX won't be fixed though. One thing I know for certain is that making ```gDPFillRectangle``` call ```drawer.clearDepthBuffer(ulx, uly, lrx, lry);``` more often fixes the issue. Maybe something changed in this area of the code.

**Comment by gonetz** [comment]
Issue on Shield is fixed: dbb827efc14

How to run EGL version in GLES3.1 mode?

**Comment by fzurita** [comment]
Here is an updated mk file that builds the gles 3.1 version


[mupen64plus-video-gliden64.txt](https://github.com/gonetz/GLideN64/files/744741/mupen64plus-video-gliden64.txt)

In Android Studio do a Build --> Clean, then Build-->Refresh Linked C++ projects.

**Comment by loganmc10** [comment]
Just so I understand, what is the goal here? Is it to get rid of the GLESX builds? What is the difference between the EGL build and the GLES builds now?

**Comment by fzurita** [comment]
I was talking it a step at a time. Here are my thoughts:
* First get all versions working again.
* After they all work again, modify the remaining #ifdefs in the code with run time checks

Step number two shouldn't be too hard since gonetz didn't leave too many.

**Comment by fzurita** [comment]
EGL can support both full OpenGL ir GLES, so ultimately, you will only have the EGL version.

**Comment by loganmc10** [comment]
OK just wanted to make sure. I'll try to get my Raspberry Pi working in the next few days, since that is a GLES2 only device, so it will be a pretty good test system for this

**Comment by fzurita** [comment]
I found the problem with enableFragmentDepthWrite causing issues with GLES 3.x. Our check was support was incorrect so it was only return true for full GL.

**Comment by fzurita** [comment]
I updated the pull request.

**Comment by fzurita** [comment]
You need to change the mupen64plus ae code so that there is only a GLideN64 gles3x version instead of 3.0 and 3.1 versions.

I'll make a branch with it correct.

**Pull request merged**
