### PR TITLE
GLideNUI: move to static Qt5.15 build

### PR DESCRIPTION
**Pull request by Rosalie241**
please re-upload the qt builds from [my repo's `qt_build` release](https://github.com/Rosalie241/GLideN64/releases/tag/qt_build) to [your repo's `qt_build` release](https://github.com/gonetz/GLideN64/releases/tag/qt_build) and change the url in `QT_BUILD_BASE_URL`, I'll update the wiki with the new qt build instructions after merging.

### CODE REVIEW

**Comment by Rosalie241** [comment]
the build failure seems to come from using platform `msvc2015`, am recompiling qt with `msvc2017` as target.

**Comment by Rosalie241** [comment]
Issues have been resolved, should be ready to merge

**Comment by gonetz** [comment]
> please re-upload the qt builds from [my repo's `qt_build` release](https://github.com/Rosalie241/GLideN64/releases/tag/qt_build) to [your repo's `qt_build` release](https://github.com/gonetz/GLideN64/releases/tag/qt_build) and change the url in `QT_BUILD_BASE_URL`,

Done. Merged: 60c07f5b600
I tested your Qt build. It works, thanks!
However, I now sometimes get internal Qt assert when dialog is started. Something about a wrong thread.
I hope that it happens only with debug build. I met no problems with release one.
Please update the wiki with the new qt build instructions

**Comment by Rosalie241** [comment]
>  However, I now sometimes get internal Qt assert when dialog is started. Something about a wrong thread.

odd, haven't experienced that myself

>  Please update the wiki with the new qt build instructions

will do, thanks for merging ❤️

**Pull request closed without merging**
