### PR TITLE
Use angrylion's magic square dither matrix

### PR DESCRIPTION
**Pull request by gizmo98**
https://github.com/gonetz/GLideN64/issues/2359

### CODE REVIEW

**Comment by gizmo98** [comment]
@ToruTheRedFox could you test a appveyor build?

**Comment by ToruTheRedFox** [comment]
image

**Comment by gizmo98** [comment]
@ToruTheRedFox 
Is the pattern ok now?

**Comment by ToruTheRedFox** [comment]
yes

**Pull request merged**
