### PR TITLE
Fix some GL Errors

### PR DESCRIPTION
**Pull request by loganmc10**
As I mentioned here:
https://github.com/gonetz/GLideN64/issues/1335#issuecomment-276447209

Having the function pointers use the exact same name as the actual OpenGL function is a problem. It breaks apitrace, which is a very useful tool in GL debugging. There might be other issues as well, I'm not sure.

This change prepends ```m_``` to the function pointers. I tested this on Linux, but I haven't tested EGL or Windows.

The 2nd commit fixes a couple extension issues. You can't rely on checking if a function pointer is NULL, sometimes an implementation will return a valid pointer even if the function is unsupported. I also added a check for ARB_compute_shader for Image Textures, since it provides glMemoryBarrier and that is required.

### CODE REVIEW

**Comment by fzurita** [comment]
Instead of a blanket search and replace, I would consider using macros to redefine those strings. For example:
```
#define glEnable m_glEnable
```

**Comment by loganmc10** [comment]
ok ill look into that

**Comment by loganmc10** [comment]
Thanks for the tip, that works as well and it's a lot cleaner. I've updated the pull request.

**Comment by loganmc10** [comment]
I've also pushed a commit to fix Image Texture support on devices with GL < 4.2. They need a couple lines in the GLSL header to work.

**Comment by loganmc10** [comment]
I've also added a commit to fix the EGL build on non-Android devices. I've tested it on Linux and it works good, I haven't tried the Raspberry Pi.

**Comment by gonetz** [comment]
'm_ ' prefix is for class members. It is confusing to use it for global functions.

I use 'g_' for global objects. 

If you don't like 'g_gl' you may use just '_gl' or '_' postfix, e.g. 'glBlendColor_'

**Comment by gonetz** [comment]
Other commits look good.

**Comment by loganmc10** [comment]
I'm fine with g_, I just did m_ because I don't know much about coding conventions, I'll correct it when I get a chance

**Comment by loganmc10** [comment]
Ok should be good now

**Pull request merged**
