### PR TITLE
UI refresh

### PR DESCRIPTION
**Pull request by Aquatakat**
I've adjusted the main page a bit:

image

Profiles changed to avoid the ambiguous state between typing a name and clicking the Add button:

image

New texture enhancements page allows copy/pasting a path without opening a new window:

image

And a bunch of other little changes. I hope you like it!

### CODE REVIEW

**Comment by CrankySupertoon** [comment]
Dont Pull Request in Master, other then that i think its good

**Comment by gonetz** [comment]
@Aquatakat 
Your modifications look good, as usual :) Thanks!
I have few notes about AA-related parameters.
* You made AA mode selection via radio buttons.
They are working not quite consistent.
If I have MSAA enabled and switch to No AA, MSAA reset to 'off'
If I have MSAA enabled and switch to FXAA, MSAA does not reset.
Why? FXAA also means that MSAA will be disabled.
* MSAA scale is from 'off' to 'high'. When user switches from No AA to MSAA, MSAA slider set to 'off' and user need to do another click to select necessary AA. I suggest to automatically set MSAA to "high" level when MSAA selected. Most users prefer max MSAA level. What do you think?

**Comment by Aquatakat** [comment]
That's probably a good idea @gonetz, I think the only reason I have those behave the way they do is because that's how the settings ini is set up. Leaving MSAA at max when the no aa/FXAA are checked is probably a good idea, I'll work on that in a few days.

**Comment by gonetz** [comment]
AA works good with latest commit, thanks!
I have two questions:
* You moved "Store compiled shaders" options at the bottom. Why? It looks alone here
* Configuration panel has plenty of blank space at the bottom, at least with my build. Can it be shrunk?
StoreShaders

**Comment by Aquatakat** [comment]
@gonetz, I just wanted to let you know I'm still working on this. I wanted to add a feature to allow a user to use per-game settings but only update a settings profile while a game is running.

image

It works well but some of the behaviour needs a little adjusting.

Also file_tex_storage is supported:

image

**Comment by gonetz** [comment]
@Aquatakat Hi Ryan,

I put your work to https://github.com/gonetz/GLideN64/tree/file_tex_starage+new_gui branch.
Test build available in WIP Builds 4, #2037
Imo, the new GUI looks good. "Texture enhancement" tab is more convenient to use now.
There is one feedback note https://github.com/gonetz/GLideN64/issues/2037#issuecomment-520398657
that information tips for antialiasing options is missing.

**Comment by gonetz** [comment]
@Aquatakat Thanks!
The changes are in master now.

**Pull request closed without merging**
