### PR TITLE
Tooltip fixes

### PR DESCRIPTION
**Pull request by Aquatakat**

### CODE REVIEW

**Comment by gonetz** [comment]
I dislike these changes.

My variant:

"This option set output render buffer size to a factor of the original N64 resolution. The buffer has size of output resolution by default, but you can output to the Original N64 resolution or a Multiple of N64 resolution."

"N64 calculates lighting per vertex. This option enables Phong shading, which provides smoother and more realistic lighting."

**Comment by Aquatakat** [comment]
One thing to note:
Factor typically refers to a number divided by some number (1/2, 1/3, 1/4, 1/6), which makes little sense in the context of the UI

**Comment by gonetz** [comment]
"This option set output render buffer size. The buffer has size of output resolution by default, but you can output to the Original N64 resolution or a Multiple of N64 resolution."

**Comment by Aquatakat** [comment]
"This option sets the output render buffer size. By default, the render buffer is set to the Same **as output resolution**, but you can set it to the **Original N64 resolution** or a **Multiple of N64 resolution**."

??

Bold options imply selectable options in the dropdown.

**Comment by gonetz** [comment]
Good

**Comment by gonetz** [comment]
Please update the pull request.

**Comment by Aquatakat** [comment]
Commit #4fc73ec looks OK to me. Am I missing something?

**Comment by gonetz** [comment]
Yes, it is ok now, thanks!

**Comment by gonetz** [comment]
General note: currently tooltip for group of elements attached only to the first element of the group.
For example, you may get tooltip for Aspect ratio only when you place cursor over "Aspect ratio:" label. IMO, it will be better to show that tooltip for any element of the group. Old GUI works that way.

**Pull request merged**
