### PR TITLE
[WIP] French translation

### PR DESCRIPTION
**Pull request by baptiste0602**
Do not merge yet ! (tooltips of Textures and Post-filters are not translated yet)

Feel free to make proposal or edit.

### CODE REVIEW

**Comment by gonetz** [comment]
Why are you trying to push your changes to master branch? I created special branch for French translation: 
https://github.com/gonetz/GLideN64/commit/67c3179757124a0d2ed80befb368854c1f4785cd

You commit should be on top of my initial commit with translations/gliden64_fr.ts

**Comment by gonetz** [comment]
Looks pretty much complete. I'll push it to the branch.

**Comment by baptiste0602** [comment]
I completed the translation.
@gonetz : could you compile and send me the file for testing before merge ? Thanks

**Comment by gonetz** [comment]
Ops! You made your changes in a wrong branch. I merged it without check :(

**Comment by gonetz** [comment]
I've put your changes in 'translations' branch. I sent you link to compiled file.

**Pull request merged**
