### PR TITLE
Fix too small threaded OpenGL buffers in some games

### PR DESCRIPTION
**Pull request by fzurita**
This is the issue for which @m4xw found a fix for as reported here:

https://github.com/gonetz/GLideN64/issues/2249

### CODE REVIEW

**Comment by gonetz** [comment]
8x increase buffer size? How did you come to that size? Is this value somehow justified?

**Comment by m4xw** [comment]
Completely forgot about that one.
I just bumped them up a bunch, this was primarily issue with nerrels texture pack so i figured its a adequate amount, but its for sure not tweaked.
I cant say I encountered issues like stated in the original issues (other than the oot new_dynarec mingw issue which isnt RDP) so your mileage might vary there (but i also have lower tex cache etc)

**Comment by m4xw** [comment]
On another note iirc the ringbuffer bump was required as well.
It would mostly choke on generating the cache on lower-end (has been ages tho so fuzzy memory)

**Comment by fzurita** [comment]
The ring buffer already has a 200MB max size.

**Comment by m4xw** [comment]
Oh i see, missed that change!

**Comment by fzurita** [comment]
@gonetz I used a value that @m4xw used thinking that it has gone through enough testing to be found as valid for our use case.

@m4xw how did you end up coming up with that number?

**Comment by m4xw** [comment]
The value was pulled out of thin air, the change wasnt deployed in the wild, this def needs to be revisted on our part!

**Comment by fzurita** [comment]
Oh, ok, I came up with the original number or if thin air as well.

None of the games I tested exceeded that number. I guess ideally it should just have a max size like the ring buffer pool.

Do you have any games that were helped by this?

**Comment by m4xw** [comment]
Majoras with very big texture packs (nerrels)
Would choke on some transitions (leaving clocktown, etc)

**Comment by fzurita** [comment]
Interesting, the two values I changed shouldn't be affected by texture size.

**Comment by m4xw** [comment]
I wonder if it was just the ringbuffer change then.
Also I can't say I heard about the issue lately, spooky stuff for sure

**Comment by fzurita** [comment]
Ok, I will close this pull request unless I hear otherwise. Not hearing much evidence that is actually needed.

**Pull request closed without merging**
