### PR TITLE
Ugly script for power users and more...

### PR DESCRIPTION
**Pull request by Jj0YzL5nvJ**
This script has as a minimum requirement to specify an architecture to start working. It will require some external CLI tools like `7z`, `git` and optionally `curl` if `--dlqt` is used.

Run without parameters to see help.

### CODE REVIEW

**Comment by Jj0YzL5nvJ** [comment]
@oddMLan, pay attention.

**Comment by oddMLan** [comment]
Looks good to me, but I don't understand why this is necessary. So that is possible to run the cmd file locally and build all projects at once? Skip the configuration step with Qt from Visual Studio?

**Comment by Jj0YzL5nvJ** [comment]
> So that is possible to run the cmd file locally and build all projects at once? Skip the configuration step with Qt from Visual Studio?

Not touch Visual Studio IDE with a ten foot pole, yes. That's true if you have the PATH environment well configured with all the additional CLI programs.
Actually it's not necessary to replace the current Appveyor. But both files share practically the same DNA, but with extended features, so... make sense?

The reason I want you to be aware of this change is because I don't know if the addition of "_x86" will break the package script used by Project64 to get GLideN64's builds, that’s all.

**Comment by oddMLan** [comment]
> The reason I want you to be aware of this change is because I don't know if the addition of "_x86" will break the package script used by Project64 to get GLideN64's builds, that’s all.

It might, but if it does then the Project64 packaging script can be modified accordingly

**Comment by oddMLan** [comment]
What did you change in the lastest two pushes?

**Comment by Jj0YzL5nvJ** [comment]
In the first, a bug that overwrited the QTDIR variable in the second loop by using "`--all`" with `MYQTDIR_x86` and `MYQTDIR_x64`.
In the second, I rearrange the sequence of some sets to remove a `goto`, and add some quotes to avoid an bug with paths with parentheses, that's all.

I think I have fixed most of the potential bugs... any feedback is welcome.

**Comment by Rosalie241** [comment]
IMO this is uglier than it was (batch is god awful to read)

why is `taskkill` needed at all? Seems like an ugly hack
and the `goto`s make the flow incredibly unreadable


```
set MSBUILDQT=msbuild
set MSBUILDWTL=msbuild
set MSBUILDM64P=msbuild
```
why? this is completely unrequired and just makes the code longer and again, uglier to read

```
set VS2013=Microsoft Visual Studio 12.0
set VS2015=Microsoft Visual Studio 14.0
set VS2017=Microsoft Visual Studio\2017
set VS2019=Microsoft Visual Studio\2019
```
why's this needed? if you've launched the dev tools cmd, you don't need this *at all*

also why `curl`, that isn't a program installed by default in windows, is it?

**Comment by Jj0YzL5nvJ** [comment]
Thx!

**Comment by Jj0YzL5nvJ** [comment]
> another 'problem' I have with this is that it's really not difficult to build GLideN64 from source 'manually' using msvc on windows, so this seems unrequired?

Try to run the IDE in a machine with 2GB of RAM or less with any modern AV to recognize what really means "fun".

**Comment by Rosalie241** [comment]
I meant that it was not difficult to build using the developer tools cmd manually

On October 16, 2020 9:12:00 PM GMT+02:00, Jj0YzL5nvJ <notifications@github.com> wrote:
>> another 'problem' I have with this is that it's really not difficult
>to build GLideN64 from source 'manually' using msvc on windows, so this
>seems unrequired?
>
>Try to run the IDE in a machine with 2GB of RAM or less with any modern
>AV to recognize what really means "fun".
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gonetz/GLideN64/pull/2358#issuecomment-710451239

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gonetz** [comment]
Is it possible to add more informative errors messaging? I run the script and got "ERROR!" And what?

**Comment by gonetz** [comment]
"7z was not found in the environment" - much better!

**Comment by gonetz** [comment]
The script works, but if I run it without parameters it just builds everything.
It is not quite a common behavior for a CLI tool. Would not it be better to print "Usage:" message instead with the list of parameters?
Also, it would be nice to print not only the name of the resulted archive but also the path to it, absolute or relative. The current message is:
"Creating archive: GLideN64-8a5d26db-WTL_for_Project64_x86.7z"
I should then guess that the actual file location is
../../build/GLideN64-8a5d26db-WTL_for_Project64_x86.7z

**Comment by Jj0YzL5nvJ** [comment]
> It is not quite a common behavior for a CLI tool. Would not it be better to print "Usage:" message instead with the list of parameters?

I had thought about adding a "help" parameter, but I think your idea is better.

> Also, it would be nice to print not only the name of the resulted archive but also the path to it, absolute or relative.

I can do two things, show the absolute path and open said path with Windows explorer. Or just do one of those two, personally I prefer to do both...

Other parameters that could be implemented could be to download Qt only if specified (--dlqt). Another would be to clean up the existing build files (--clean).
And with all this it would make more sense if I remove the options to configure functions that are already controlled by parameters...

**Comment by gonetz** [comment]
Yes, it sounds good.

**Comment by Jj0YzL5nvJ** [comment]
I really need feedback from people messing with the parameters and variables.

**Comment by gonetz** [comment]
Just tested - it looks and works as a really good and useful script now. Thanks!

**Pull request merged**
