### PR TITLE
Fixed blurry icon in main window

### PR DESCRIPTION
**Pull request by oddMLan**
Handcrafted icon in small sizes for optimal view, main window icon doesn't look blurry anymore

Made proper icons for sizes 16x16, 24x24, 32x32, 48x48, 128x128 and 256x256
the last two are PNG-compressed but since Windows Vista the .ico format allows it, hopefully this won't be an issue with QT (haven't found any mention of that).

Not only that but the resulting icon file is 4.2 kb smaller.

### CODE REVIEW

**Comment by oddMLan** [comment]
Old icon
old

New icon
new

**Comment by oddMLan** [comment]
16x16
gliden64 16x16
24x24 (Windows 10 taskbar icon size)
gliden64 24x24
32x32 (Windows 7/8 taskbar size)
gliden64 32x32
48x48
gliden64 48x48
128x128
gliden64 128x128
256x256
gliden64 256x256

**Comment by Aquatakat** [comment]
I wonder if the icon should also have a transparent background?

**Comment by gonetz** [comment]
No. White background is ok.

**Comment by gonetz** [comment]
Merged: 6e15de2e
Thanks!

**Comment by gonetz** [comment]
> No. White background is ok.

I'm not a designer, so my No is just an opinion.

**Comment by Aquatakat** [comment]
It's not often shown but it doesn't matter too much.

I think to make it work without the white background there might have to be some stylised changes to the icon. Some icons look nice against all backgrounds, like PJ64: 
image

Some look awful, like Dxtory: 
image

The white background looks a bit odd in some places but in general it at least leaves it legible.

**Comment by oddMLan** [comment]
I thought about making it transparent, but that particular shade of green wouldn't work against all backgrounds, IMO.
It could work if I made it have just a white outline maybe. 

just outline

Would this look better?

**Comment by Aquatakat** [comment]
A full white outline is stark. You could reduce the opacity of the white to 50% or something maybe.

**Comment by oddMLan** [comment]
I think it looks alright. Icons are supposed to look solid against all backgrounds. Look at PCSX2's icon, it also has a white outline.

**Comment by oddMLan** [comment]
just outline
Looks a tad better with a matching yellowish gray.

**Comment by Aquatakat** [comment]
I hand painted something that might be what it might look with a white with a 50% opacity border:

image

I do like the yellowish gray better than the full white though.

**Comment by gonetz** [comment]
I forgot to close that pull request. If you will do another version of the icon, please make new pull request.
Also, it is better to push icons changes to New GUI branch, otherwise I may have problems with merge in future.

**Pull request closed without merging**
