### PR TITLE
Make compatible with apitrace in Debug mode

### PR DESCRIPTION
**Pull request by loganmc10**
apitrace is incompatible with GL_MAP_COHERENT_BIT. This change allows apitrace to work properly when GLideN64 is compiled in Debug mode, when it is compiled in Release mode, it still uses GL_MAP_COHERENT_BIT, which is the fastest way to map the buffer.

This fixes: https://github.com/gonetz/GLideN64/issues/1359

### CODE REVIEW

**Comment by orbea** [comment]
Thanks for doing this, but I tried this PR and it segfaults mupen64plus.
```
Thread 1 "mupen64plus" received signal SIGSEGV, Segmentation fault.
0x00007ffff7436ba0 in __memcpy_ssse3 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7436ba0 in __memcpy_ssse3 () from /lib64/libc.so.6
#1  0x00007fffec890938 in ?? () from /usr/lib64/xorg/modules/dri/nouveau_dri.so
#2  0x00007fffec8948b2 in ?? () from /usr/lib64/xorg/modules/dri/nouveau_dri.so
#3  0x00007fffec6771b1 in ?? () from /usr/lib64/xorg/modules/dri/nouveau_dri.so
#4  0x00007fffec5ff0eb in ?? () from /usr/lib64/xorg/modules/dri/nouveau_dri.so
#5  0x00007fffec5ff356 in ?? () from /usr/lib64/xorg/modules/dri/nouveau_dri.so
#6  0x00007fffec5ff758 in ?? () from /usr/lib64/xorg/modules/dri/nouveau_dri.so
#7  0x00007fffefec8e9b in opengl::Update2DTexSubImage::update2DTexture (
    this=0x691200, _params=...)
    at /tmp/SBo/GLideN64/src/Graphics/OpenGLContext/opengl_TextureManipulationObjectFactory.cpp:243
#8  0x00007fffefec32ca in opengl::ContextImpl::update2DTexture (this=0x840070,
    _params=...)
    at /tmp/SBo/GLideN64/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp:193
#9  0x00007fffefeb6d8b in graphics::Context::update2DTexture (
    this=0x7ffff06d8220 <gfxContext>, _params=...)
    at /tmp/SBo/GLideN64/src/Graphics/Context.cpp:105
#10 0x00007fffefeb3ec6 in RDRAMtoColorBuffer::copyFromRDRAM (
    this=0x7ffff06d80a0 <RDRAMtoColorBuffer::get()::toCB>, _address=640,
    _bCFB=true) at /tmp/SBo/GLideN64/src/BufferCopy/RDRAMtoColorBuffer.cpp:252
#11 0x00007fffefe7bbfd in FrameBuffer_CopyFromRDRAM (_address=640, _bCFB=true)
    at /tmp/SBo/GLideN64/src/FrameBuffer.cpp:1108
#12 0x00007fffefeac8bd in VI_UpdateScreen () at /tmp/SBo/GLideN64/src/VI.cpp:160
#13 0x00007fffefeb6559 in PluginAPI::UpdateScreen (
    this=0x7ffff06d8210 <PluginAPI::get()::api>)
    at /tmp/SBo/GLideN64/src/common/CommonAPIImpl_common.cpp:229
#14 0x00007fffefe6ed79 in UpdateScreen ()
    at /tmp/SBo/GLideN64/src/CommonPluginAPI.cpp:43
#15 0x00007ffff5654a1e in vi_vertical_interrupt_event (
    vi=vi@entry=0x7ffff69d34d0 <g_dev+17842992>)
    at ../../src/device/vi/vi_controller.c:141
#16 0x00007ffff5647f31 in gen_interupt ()
    at ../../src/device/r4300/interupt.c:547
#17 0x00007fffe30472bb in ?? ()
#18 0x00007ffff58cf1a0 in ?? () from /usr/lib64/libmupen64plus.so.2
#19 0x00007ffff56a08e2 in dyna_start (code=0xffffffff8001f7b6)
    at ../../src/device/r4300/x86_64/rjump.c:57
#20 0x00007ffff6dd3840 in ?? () from /usr/lib64/libmupen64plus.so.2
#21 0x00007fffffffdee0 in ?? ()
#22 0x00007fffffffdea0 in ?? ()
#23 0x00007ffff6dd38c0 in rsp () from /usr/lib64/libmupen64plus.so.2
#24 0x00007ffff564c020 in ?? () from /usr/lib64/libmupen64plus.so.2
#25 0x00007ffff58cf1a0 in ?? () from /usr/lib64/libmupen64plus.so.2
#26 0x00007ffff564c24c in run_r4300 () at ../../src/device/r4300/r4300_core.c:166
#27 0x00007ffff5637ae5 in run_device (dev=dev@entry=0x7ffff58cf1a0 <g_dev>)
    at ../../src/device/device.c:90
#28 0x00007ffff565649b in main_run () at ../../src/main/main.c:1026
#29 0x0000000000402050 in main (argc=2, argv=0x7fffffffe218)
    at ../../src/main.c:782
```
GDB log - http://pastebin.com/nvWuMFJR

**Comment by loganmc10** [comment]
Whoops sorry about that, thanks for the backtrace. I've updated the pull request, can you try it again?

**Comment by orbea** [comment]
That works and I can additionally replay apitraces made with a debug build now, thanks!

**Comment by gonetz** [comment]
merged: acff19e66c

**Comment by gonetz** [comment]
A question: can apitraces (or other tool) detect OpenGL resources leaks? I'm not sure that I free all allocated GL objects.

**Comment by loganmc10** [comment]
Yes apitrace says it supports it:

https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown#identify-opengl-object-leaks

I tested a trace from Mario Tennis and it didn't print anything, so I assume that means there are no leaks?

The documentation says:
> apitrace provides very basic leak tracking: it tracks all textures/ framebuffers/renderbuffers/buffers name generate and delete call. If a object is not deleted until context destruction, it's treated as 'leaked'.

There may be better tools that can detect when an object could/should be deleted or something, I'm not sure.

**Comment by gonetz** [comment]
Lets test, can we trust apitrace results. Could you disable some resource removal,  for example do nothing in ZlutTexture::destroy()  and disable m_monochromeProgram.reset() in CombinerInfo::destroy()? Will apitrace  detect it?

**Comment by loganmc10** [comment]
My machine doesn't support image textures so I don't think the ZlutTexture thing would make a difference. I commented out m_monochromeProgram.reset() and it didn't complain about anything (I tried Smash Bros).

I commented out ```glDeleteTextures(1, &glName);``` in ```ContextImpl::deleteTexture``` and I get this:

```
646: error: texture 1 was not destroyed until 359948
659: error: texture 2 was not destroyed until 359948
660: error: texture 3 was not destroyed until 359948
680: error: texture 4 was not destroyed until 359948
836: error: texture 5 was not destroyed until 359948
872: error: texture 6 was not destroyed until 359948
881: error: texture 7 was not destroyed until 359948
890: error: texture 8 was not destroyed until 359948
899: error: texture 9 was not destroyed until 359948
908: error: texture 10 was not destroyed until 359948
917: error: texture 11 was not destroyed until 359948
926: error: texture 12 was not destroyed until 359948
...
...
...
```

So it seems like it's probably working?

**Comment by gonetz** [comment]
Ok, it can detect texture not destroyed, but can't detect shader program not destroyed. Half working. At least we know that all our textures correctly freed.

**Pull request closed without merging**
