### PR TITLE
Update pokemon snap settings

### PR DESCRIPTION
**Pull request by tony971**
Attempt two since I'm not good enough with github to correct the original.

### CODE REVIEW

**Comment by AmbientMalice** [comment]
The problem is frameBufferEmulation\copyFromRDRAM=1, which makes the game unstable and causes constant flickering because the feature is broken in a variety of ways.

**Comment by tony971** [comment]
But the red dot won't appear without it.

**Comment by tony971** [comment]
I think you might have meant copyToRDRAM=1

**Comment by AmbientMalice** [comment]
>But the red dot won't appear without it.

That's my point. Using the framebuffer as a fullscreen texture makes quite a few games unstable. At least, it did last time I checked. Snap seems to crash with it enabled.

**Comment by tony971** [comment]
It's the copyToRDRAM that causes constant flickering and crashing for me. copyFromRDRAM hasn't shown any negative side effects on my end.

**Comment by gonetz** [comment]
Added

**Pull request closed without merging**
