### PR TITLE
change msvc15 to msvc14

### PR DESCRIPTION
**Pull request by rez-**
Renamed msvc15 directory to msvc14 because Visual Studio 2015 has actually Visual C++ version 14.

Anyhow great work gonetz and all other contributors!

### CODE REVIEW

**Comment by gonetz** [comment]
merged: 764275887

**Comment by fzurita** [comment]
This seems like a strange pull request. Most other projects I've seen go by visual studio version, not Visual C++ version.

**Comment by gonetz** [comment]
Visual studio 13 project already in msvc12 and I will not change it. So, msvc14 following the same logic.

**Comment by gonetz** [comment]
I agree, go by visual studio version is less confusing.

**Comment by gonetz** [comment]
I reverted this commit and renamed msvc15 to msvc2015. This is QT style. For example: 
win32-msvc2015
# Written for Microsoft Visual C++ 2015
msvc2015 is less confusing than msvc14.

**Comment by rez-** [comment]
Then shouldn't we update the msvc12 directory to msvc2013 as well?

**Comment by gonetz** [comment]
We should, but we will not. I use MSVS2013 to find regressions. It will be very inconvenient for me to check older commits if project folder will be renamed.

**Pull request closed without merging**
