### PR TITLE
Updated translations

### PR DESCRIPTION
**Pull request by Felipefpl**
Please, take a look at how the translations look in all tabs/sections once compiled, apparently Glide doesnt support the expansion of the GUI for translated words (which are larger in other languages than english)

### CODE REVIEW

**Comment by gonetz** [comment]
> apparently Glide doesnt support the expansion of the GUI for translated words

It is possible. Most of translations are outdated and the current GUI layout is tested only with English.

**Comment by gonetz** [comment]
I checked your work. GUI with Portuguese translation is wider than English one:
GUI_translated
It looks fine. Merged: 189afd3996
Thanks!

**Comment by Felipefpl** [comment]
Thanks for checking, any idea when a new release will come?

**Comment by gonetz** [comment]
It was planned yet the last year, but still there are regressions, which must be fixed before the release.

**Comment by Felipefpl** [comment]
I see, good to know it's coming.

**Pull request closed without merging**
