### PR TITLE
disable copy color by default 

### PR DESCRIPTION
**Pull request by purplemarshmallow**
+typo fix

### CODE REVIEW

**Comment by AmbientMalice** [comment]
Is there any particular reason for this change? This will mean having to re-enable RDRAM copies for every single game that needs them.

**Comment by purplemarshmallow** [comment]
Yes see https://github.com/gonetz/GLideN64/pull/799
async fb copies can be dangerous

**Comment by AmbientMalice** [comment]
Shouldn't it be set back to sync copies by default, then? Or simply set to sync on the games where async causes crashes/problems?

**Comment by purplemarshmallow** [comment]
async can't be default. The default settings should be safe. Maybe another game has the same problem as Donkey Kong 64. Enabling sync by default would be an option. But I think it's bad. It costs a lot of performance and many users complained about bad performance. Perfect solution would be to have emulator notifications.

**Comment by AmbientMalice** [comment]
>Perfect solution would be to have emulator notifications.
That would be ideal, yes. It would also cure related problems.

**Comment by purplemarshmallow** [comment]
Not sure what's the right thing to do. The current ini file has many entries of games that need RDRAM copies.

**Comment by purplemarshmallow** [comment]
I'll colse for now. If copy to RDRAM is disabled by default this possibly needs more testing

**Pull request closed without merging**
