### PR TITLE
german translation: fix special signs

### PR DESCRIPTION
**Pull request by gizmo98**
Replace html special sign notation with xml notation.

@gonetz 
Please take a look if there is no error now.

XML validator says there is no error anymore.

### CODE REVIEW

**Comment by gonetz** [comment]
You should use QT Linguist tool to avoid such problems.
I open the translation file with QT Linguist, so the problem with xml is fixed, file can be opened.
However, there are plenty of "Translation does not end with the same punctuation as the source text" errors. For example:  "Correction-level:" => "Korrekturwert", colon is missing.
There are many missing translations for tooltips. All these errors are easy to find and fix with QT Linguist.

**Comment by gizmo98** [comment]
Ok. I will use Qt Linguist Tool and update the PR.

**Comment by gizmo98** [comment]
All "ends with different punctuation" and "missing translation" points are fixed now.

**Comment by gonetz** [comment]
Cool! Looks great, thanks!
Merged.

**Pull request closed without merging**
