### PR TITLE
 Optimize Perfect Dark framebuffer effects 

### PR DESCRIPTION
**Pull request by purplemarshmallow**

### CODE REVIEW

**Comment by oddMLan** [comment]
Do you have a build?

**Comment by purplemarshmallow** [comment]
https://drive.google.com/file/d/0B7Y6r4SpC_QQQ1ZRVWRqWHgyRm8/view?usp=sharing

**Comment by AmbientMalice** [comment]
Seems to work rather well, especially in high resolution mode. Wonder whether any other games are affected/improved?

**Comment by purplemarshmallow** [comment]
It seems to affect only Perfect Dark during camspy or IR vision effects. I don't know any other game where this makes a noticeable difference. But maybe there are other games with the same problem.

**Comment by purplemarshmallow** [comment]
But it breaks portraits in Pokemon Stadium 2 :/

**Comment by AmbientMalice** [comment]
>But it breaks portraits in Pokemon Stadium 2 :/

Is there *anything* that doesn't break Pokemon Stadium 2?

**Comment by purplemarshmallow** [comment]
I have a better idea. I should check once per frame

**Pull request closed without merging**
