### PR TITLE
Minor improvements 2

### PR DESCRIPTION
**Pull request by gizmo98**
-use a u32 s32 union to load, store and insert matrix values
-ZSortBOSS_Audio2(): use absolut value of fraction

### CODE REVIEW

**Comment by theboy181** [comment]
What improvements can be witnessed from this commit?

**Comment by theboy181** [comment]
Thank! improvements are always rewarding. I'm sure there are benefits. :)

**Comment by gonetz** [comment]
@gizmo98 The idea is good, thanks!
I moved matrix element conversion to separate functions.
The code is in https://github.com/gonetz/GLideN64/tree/gizmo98-minor-improvements-2 branch.
Please take a look. Do you know, which games use gSPInsertMatrix?
It would be good to test that function.

**Comment by gizmo98** [comment]
@gonetz 
Thanks! Your modifications look much more polished. Nice job. I‘m on vacation atm. I will test your branch in two weeks.

According to this old thread Super Smash Bros uses gSPInsertMatrix. http://www.emutalk.net/threads/12288-glNintendo64()-v0-3/page8

Just another question. We load a s32 4x4 matrix from RDRAM and convert it to 4x4 float matrix. Float has a 23Bit mantissa. Float cannot store all possible s32 values. Wouldn‘t it be better to use a 4x4 double matrix?

**Comment by weinerschnitzel** [comment]
IIRC, it is Kirby's Dreamland stage that uses insert matrix with the trees.

**Comment by gonetz** [comment]
I'll test SSB and Kirby, thanks!

Regarding double for matrix: I'm sure that float precision is enough for 3D graphics, at least of N64 level. We do not need to keep any possible s32 value in float. Values of matrix elements are quite limited.

**Comment by gonetz** [comment]
Tested. Works correct. Merged.

**Comment by theboy181** [comment]
What does this fix? Any visual improvements?” To SSB like the Kirby stage?

**Comment by gonetz** [comment]
@theboy181 You already asked this question. This commit is about code improvements.

**Pull request merged**
