### PR TITLE
gSPObjSprite: Fix Yoshi's Story's petals

### PR DESCRIPTION
**Pull request by gizmo98**
Fix cut off petals. I always thought there is one texel missing.
I have tested Mischied Makers, Worms, Paper Mario, Legend of Zelda OOT and have seen no regressions.

### CODE REVIEW

**Comment by gizmo98** [comment]
Sorry. Do you know any other game using this function?

**Comment by gonetz** [comment]
Many games use functions from S2DEX, but I'm not sure about Sprite.
Parlor! uses Sprite command for sure, I just fixed problem with it.

**Comment by gonetz** [comment]
Btw, the same code is used in ObjCoordinates ctor:
```
	ObjCoordinates(const uObjSprite *_pObjSprite, bool _useMatrix)
	{
...
		uls = ult = 0;
		lrs = (f32)(data.imageW - 1);
		lrt = (f32)(data.imageH - 1);

```

It is inherited from the original Orkin's code:
```
	gSP.vertices[2].s = imageW - 1;
	gSP.vertices[2].t = imageH - 1;
```

**Comment by theboy181** [comment]
I think SD Hiryuu is S2DEX, Do you guys know if there is a way to search the memory to confirm that the S2DEX microcode is being used? can I simple search for the string S2DEX?

**Pull request closed without merging**
