### PR TITLE
GLIdeN64.cusom.ini All Actual (29.04.15) Custom-Settings

### PR DESCRIPTION
**Pull request by Predator82Germany**

### CODE REVIEW

**Comment by purplemarshmallow** [comment]
gonetz wrote:

Important: Checksum for Japanese roms are converted to upper case for uniformity.
Checksums with lowercase characters will not work!

**Comment by gonetz** [comment]
Good point. @Predator82Germany, please update your commit with all section name characters in upper case.

**Comment by Predator82Germany** [comment]
I don´t know how I can change a pull request

**Comment by gonetz** [comment]
Hmm, I also can't see how to reject pull request. Help needed :)

Ok, correct file and do new pull request. Or attach the ini file here and will push it myself.

**Comment by Predator82Germany** [comment]
Now I´ve found

**Comment by gonetz** [comment]
Done

**Pull request closed without merging**
