### PR TITLE
Enabled FBInfo for Rat Attack

### PR DESCRIPTION
**Pull request by loganmc10**
I finally got this game working with mupen64plus. Strangely, unless FBInfo is enabled the game will lock up before trying to go in-game, sometimes complaining about an unknown opcode.

### CODE REVIEW

**Comment by gonetz** [comment]
> Strangely, unless FBInfo is enabled the game will lock up before trying to go in-game, sometimes complaining about an unknown opcode.

Yes, it is strange. Have you tried to disable fb emulation? May be the plugin writes something wrong into RDRAM.

**Comment by loganmc10** [comment]
Yea disabling FB emulation also fixes the problem, but the graphics look all wrong. I didn't try too many other options

It's just a bit strange because it actually seems to affect the execution of the game when it gets it wrong

**Comment by loganmc10** [comment]
"Copy auxiliary color buffers to N64 memory" also fixes the problem, instead of FBInfo

**Comment by gonetz** [comment]
> Yea disabling FB emulation also fixes the problem, but the graphics look all wrong. 

Most likely the plugin writes something wrong into RDRAM and the game hangs. It needs to be investigated, but I hardly will find time on it in near future. I'll accept this change, but someday it should be reconsidered.

**Pull request merged**
