### PR TITLE
ObjCoordinates: Implement G_OBJRM_BILERP (2D texture fix)

### PR DESCRIPTION
**Pull request by gizmo98**
- Worms Armageddon: Menu items, 2D elements and worms are no longer blurred and washed out
- Kirby Crystal Shards: Menu items and titel screen are much sharper
- Yoshi's Story: background image seem to look better
- Rewrite lrx, ulx, lry, uly, lrs, uls, lrt, ult calculation. First step: calculate image coords. Second step: calculate screen coords with scale and image coords.
- Only allow 2Bit fractional "fixed point" precision for image coords.
- Implement SHRINKSIZE 1 and 2 according to programmers guide.
- Implement G_OBJRM_BILERP according to programmers guide. Subtract 0.5 from image coords if G_OBJRM_BILERP is set. This is the main fix for bad looking textures.
> Corrects for the 0.5 slippage of the texture that occurs when bilinear interpolation is performed.  
> For example, by setting bilinear interpolation on and off, texture coordinates will vary by 0.5. S2DEX Microcode has been designed to correct these effects at the RSP to minimize the user's efforts to get around these problems.
- I have not seen any regression in other games

@gonetz 
Implementing G_OBJRM_BILERP coord correction in drawScreenSpaceTriangle(), drawTexturedRect() and gSPDrawObjRect() could fix other bad looking 2D texture problems.

### CODE REVIEW

**Comment by theboy181** [comment]
Can I HAZ build for testing?

**Comment by theboy181** [comment]
I was able to acquire a build, and test.

I don't see any improvement in Worms, only a regression. 
image
There is a black line in the BG. The worms look just as blurry too. What settings should I test with? I have render elements in N64 resolution.

**Comment by gizmo98** [comment]
Do you have an old build for comparison? My current master build looks „much more“ blurry. Names of worms are washed out. Main menu flags are blurry. 

Is PJ64 doing anything different? Becauses boxes around worm names look different. I use a GLES2 build. OGL or GLES3.1 could be different. I will test.

**Comment by theboy181** [comment]
https://discord.gg/ufGJAw

**Comment by gizmo98** [comment]
@theboy181 take a look at the lower right bars in worms armageddon. Old revision looks wrong.

**Comment by olivieryuyu** [comment]
Interesting

**Comment by theboy181** [comment]
I’ll check In the am. It is neat that you managed to fix aerofighter though.

**Comment by gizmo98** [comment]
@theboy181 If i compare my worms image with your worms images there is another big difference. Look at the waves. If i look at your images there is always a black border around wave textures. Strange.

**Comment by olivieryuyu** [comment]
For the ucode I can tell u that G_OBJRM is a command which impacts various other drawing commands.

**Comment by gizmo98** [comment]
@olivieryuyu 
Only gSPBgRect1Cyc() and gSPBgRectCopy() use coord correction atm. Most gSPObj, gSPSprite and gSPBg functions call drawer.drawScreenSpaceTriangle(). I have not tested if moving coord correction there fixes other problems or adds regressions. It's a interesting candidate for improvements.

gSPObjRectangle() --> gSPDrawObjRect() --> drawer.drawScreenSpaceTriangle()
gSPObjRectangleR() --> gSPDrawObjRect() --> drawer.drawScreenSpaceTriangle()
gSPBgRect1Cyc() --> gSPDrawObjRect() --> drawer.drawScreenSpaceTriangle()
gSPBgRectCopy() --> gSPDrawObjRect() --> drawer.drawScreenSpaceTriangle()
gSPObjSprite() --> drawer.drawScreenSpaceTriangle()
gSPSprite2DBase() --> drawer.drawScreenSpaceTriangle() 
gSPObjLoadTxSprite() --> gSPObjSprite() --> drawer.drawScreenSpaceTriangle()
gSPObjLoadTxRect() --> gSPObjRectangle() --> gSPDrawObjRect() --> drawer.drawScreenSpaceTriangle()
gSPObjLoadTxRectR() --> gSPObjRectangleR() --> gSPDrawObjRect() --> drawer.drawScreenSpaceTriangle()

**Comment by olivieryuyu** [comment]
just tested with the version posted on discord. 

Seems there is quite some issues

sans titre

**Comment by gizmo98** [comment]
@olivieryuyu 
I cannot reproduce this (raspberry pi 3b, gles2.0, mupen64plus build from current master, rsp-hle build from current master).
[mupen64plus.txt](https://github.com/gonetz/GLideN64/files/2263584/mupen64plus.txt)

img_8898

**Comment by oddMLan** [comment]
@everyone
Make sure you delete any shaders cache

**Comment by gizmo98** [comment]
Current master looks like this for me:

olivieryuyu problem...
img_8904
...and the wave problem.
img_8905

**Comment by gizmo98** [comment]
A Linux x86 build with Intel Atom looks like olivieryuyu's and theboy181's results. Seems to be a difference between arm and x86 builds or OpenGL and GLES.

**Comment by theboy181** [comment]
So this means that there needs to be adjustments for OpenGL?  I’m not a video plung expert.

**Comment by gizmo98** [comment]
@theboy181 i will do some tests with my x86 machine. This will take some time. I don‘t know the reason. I just see there is a difference between different hardware. If i get better results i will update this PR.

**Comment by gizmo98** [comment]
There are small differences between gles2's and other gl version's bilinear and 3point glsl shaders.  Can someone with GLES2 and GLES3 devices test if there is a difference? @fzurita  @loganmc10?

**Comment by olivieryuyu** [comment]
confirmed!! 

See my comments in https://github.com/gonetz/GLideN64/issues/936

seems something goes wrong since a while for upscaling

**Comment by theboy181** [comment]
What is the zilmarspec version settings.

**Comment by gizmo98** [comment]
@theboy181 
GLideNUI: Internal Resolution: Original N64 Resolution (Most accurate)

**Comment by olivieryuyu** [comment]
i tested again worms in native res and indeed it looks better, less blurry. now the matter is to understand how to fix the upscaling i guess.

**Comment by gizmo98** [comment]
@gonetz 
I think there is still a flaw if SHRINKSIZE1 is used. I correct ST values to get a 0.5f perimeter around a image. So the S value will shift 0.5f to the right and T value will shift to the left. lrx and lry values will be calculated according to programmers manual (lrx = ulx + frameW - 1/scaleW = ulx + ( lrs - uls ) / scaleW ). Bilinear filtering will produce a blurred image because TexCoords will be 0.5f off from the correct filtering position. Actually ST values shouldn't be changed. Around the "filtered" image there should be a 0.5f texel perimeter. I didn't know how to accomplish this in gsp.cpp. I think this can only be accomplished somewhere deeper after texture filtering.

SHRINKSIZE2 is correct because an one texel integer perimeter is used and the filtering position is right. 

I think the current solution is better than the old one because lrx and lry values will be calculated correctly and there is a 0.5f texel perimeter around a image. Old solution's TexCoords were always 0.5f off from the correct filtering position. So there is still room for improvement.

**Comment by gizmo98** [comment]
@gonetz do you mean the title screen majora's mask? Even with NativeResolutionFactor = 1? 
_loadBGImage() and gSPBgRect1Cyc() have some `(config.generalEmulation.hacks & hack_ZeldaMM) != 0` checks. gSPBgRect1Cyc() is using ObjCoordinates. Could be one of this hacks is doing TexCoord correction already unintentional. If ZeldaMM is the only game with issues a ZeldaMM check could be added.

			if (((gSP.objRendermode&G_OBJRM_BILERP) != 0) && ((config.generalEmulation.hacks & hack_ZeldaMM) == 0)) {
				uls -= 0.5f;
				ult -= 0.5f;
				lrs -= 0.5f;
				lrt -= 0.5f;
			}

**Comment by olivieryuyu** [comment]
Even in Native res it has the issue during the intro when pressing start when the mask turns in the black. Now the issue could be related to the framebuffer effects (i guess coming from the hack) to have the blurriness on the mask and which is applied on the 2D as well by side effect. Potentially it is the hack the issue, though I am not sure :)

**Comment by theboy181** [comment]
for some reason the text I reported in AeroFighters doesn't look as good with this build.

**Comment by theboy181** [comment]
In AeroFighters look at the text when you select " try to adjust game to fit"
image
vs any other mode.
image

**Comment by gizmo98** [comment]
@theboy181 
Mupen64plus NativeRes GLideN64 current master:
img_8969

**Comment by olivieryuyu** [comment]
new bug: https://github.com/gonetz/GLideN64/issues/1880

**Comment by gizmo98** [comment]
@olivieryuyu 
Current master or discord build?

**Comment by olivieryuyu** [comment]
error from my side, it is in LLE...

**Comment by gonetz** [comment]
> Could be one of this hacks (or _copyDepthBuffer) is doing TexCoord correction already unintentional.

No, it could not. I don't see how hack_ZeldaMM can affect coordinates. I suppose the issue with motion blur reveals a flaw in your fix. Coordinates must be calculated precisely to motion blur work correctly.
Which issue fixes the code for G_OBJRM_BILERP? May be we can remove it?

Regarding fix of filtering issues via texture coordinates: we probably can use shader instead. TexrectDrawer already uses specialized shader for bilinear filtering. I just need to understand, what is so special in filtering when SHRINKSIZE is sued.

**Comment by gonetz** [comment]
I guess, textures in Worms have black background. Many games use bright-green or purple background for bilinear-filtered textures, and these textures have green/purple outline. It is because bilinear filtering interpolates colors of neighbor pixels for given pixel, and neighbors for pixels on the rect's bounds have black/green/purple color.

**Comment by gizmo98** [comment]
@gonetz Original game footage has at least no black lines around waves:
http://www.ign.com/articles/2000/01/19/worms-armageddon-interview

Is ZeldaMM using cycleType.G_CYC_FILL? I have no time today but i will test this tomorrow:
```
		// G_CYC_COPY and G_CYC_FILL do not allow texture filtering
		if (gDP.otherMode.cycleType < G_CYC_COPY) {
			// Correct texture coordinates -0.5f if G_OBJRM_BILERP 
			// bilinear interpolation is set
			if ((gSP.objRendermode&G_OBJRM_BILERP) != 0) {
				uls -= 0.5f;
				ult -= 0.5f;
				lrs -= 0.5f;
				lrt -= 0.5f;
			}
```

**Comment by gonetz** [comment]
> Original game footage has at least no black lines around waves:

Yes. black/green/purple outline caused by bilinear filtering in high resolution. Of course, it is not present on original hardware.

> Is ZeldaMM using cycleType.G_CYC_FILL?

Err, no. G_CYC_FILL is for fillrects only. Bg commands do not use this mode.

**Comment by olivieryuyu** [comment]
zelda MM uses 0x0B and 0x09 commands at this point.

0x0B is Objrendermode and 0x09 is BG_1CYC.

BG commands are complex commands. There is a lot of warnings and details in the manual. 

Super hard stuff!

**Comment by gizmo98** [comment]
@gonetz 
Is -DDEBUG_DUMP supported under linux? I can find it in visual studio project files. But i cannot find it in CMakList.txt:
https://github.com/gonetz/GLideN64/blob/master/src/CMakeLists.txt#L308

I just want to check gDP.otherMode.l, gDP.otherMode.h, cycle mode and gSP.objRendermode if  (gSP.objRendermode&G_OBJRM_BILERP) != 0. Could be there is a difference between kirby, zelda and worms. According to programmers manual _The RSP’s correction process corresponds to the RDP’s mode_.

http://ultra64.ca/files/documentation/online-manuals/functions_reference_manual_2.0i/gsp/gSPObjRenderMode.html
`Many drawing parameters exist in the RDP to control sprite and BG drawing. Depending on the RDP mode, polygon drawing and rectangle drawing processes are affected in some subtle ways. For example, by setting bilinear interpolation on and off, texture coordinates will vary by 0.5. S2DEX microcode has been designed to correct these effects at the RSP to make it easier for you to get around these problems. The RSP’s correction process corresponds to the RDP’s mode. We call the RSP’s correction mode "object render mode" (or OBJ render mode).
`

**Comment by olivieryuyu** [comment]
@gizmo98 

from a microcode point of view, objrendermode works with magical values (I meant constants) which is not documented in the manual and affects various calculations for various commands. On top there is the filtering RDP issue to manage.

This stuff is really hard to crack down..

On question though, was G_OBJRM_NOTXCLAMP and G_OBJRM_WIDEN implemented?

**Comment by gizmo98** [comment]
@olivieryuyu 
I just wanted to see if one of those flags is set. I don't think they are implemented at the moment. I have found no implementation.

I'm quite sure the cleanest and hardest solution would be to decipher the ucode.

**Comment by olivieryuyu** [comment]
@gizmo98 

sure, however the microcode is actually so complex that I am really sure I can do such a job, except may be for one or two commands where really necessary.

I think (may be wrong) that G_OBJRM_NOTXCLAMP is used in Nintama Randou and potentially explains the issue with the square. I guess clamping means get rid of some pixels around the texture.

Any help at any level is super appreciated!

**Comment by gonetz** [comment]
@gizmo98 debug dump must work under Linux. However, there are two problems:
* DEBUG_DUMP is not defined in cmake project indeed. You may add somewhere
```
  add_definitions(
    -DDEBUG_DUMP
  )

```
* Debug log started when you press 'g' button, see line 118 in VI.cpp
isKeyPressed is not implemented  for Linux. Thus, you need to hack this place somehow, for example force call SwitchDump.

**Comment by gizmo98** [comment]
@olivieryuyu 
You can test this branch:
https://github.com/gonetz/GLideN64/compare/master...gizmo98:zelda-fix2?expand=1

It's not ready for a PR but it already does following things:
-ZeldaMM: fix motion blur effect
-Nintama Randou: fix one pixel texture seams
-Bakuretsu Muteki Bangaioh: fix bad texture quality
-Worms and Kirby still need nativeRes=1 to look good
-Aerofighter: intro text is still readable

**Comment by olivieryuyu** [comment]
@gonetz 

can you please compile a binary? :)

@gizmo98 

interesting! I guess worms and kirby can be related to filtering if native res looks goods.

**Comment by olivieryuyu** [comment]
mode 0x09 for gSPObjRenderMode in worms. So it is both G_OBJRM_NOTXCLAMP	 and G_OBJRM_BILERP.

**Comment by gizmo98** [comment]
Yep. Worms uses G_OBJRM_BILERP and G_OBJRM_NOTXCLAMP	. Kirby uses G_OBJRM_BILERP and gDP.otherMode.textureFilter == 0x02. ZeldaMM does not use G_OBJRM_NOTXCLAMP and gDP.otherMode.textureFilter == 0x02. 

[This part of code ](https://github.com/gonetz/GLideN64/compare/master...gizmo98:zelda-fix2?expand=1#diff-69d8715ec7f9fd627ec4f5516edd003dR2097)will not be executed if ZeldaMM is running.

**Comment by gizmo98** [comment]
Comparison of current master without G_OBJRM_BILERP coord correction and the branch i have posted above which fixes lrx/lry calculation for Bakuretsu Muteki Bangaioh and Nintama Randou. I would be glad if someone could test this branch. 

Current master without G_OBJRM_BILERP coord correction:
bangaioh-006
bangaioh-008
bangaioh-012
kirby64-004
kirby64-007
kirby64-009
nintamagamegallery64-010
nintamagamegallery64-013
nintamagamegallery64-015
worms_n64-010
worms_n64-013
worms_n64-017
zelda_majora s_mask-014

My current branch https://github.com/gonetz/GLideN64/compare/master...gizmo98:zelda-fix2?expand=1:
bangaioh-000
bangaioh-001
bangaioh-005
kirby64-000
kirby64-001
kirby64-002
nintamagamegallery64-002
nintamagamegallery64-004
nintamagamegallery64-007
worms_n64-000
worms_n64-003
worms_n64-007
zelda_majora s_mask-005

**Comment by olivieryuyu** [comment]
amazing! Awaiting to get from Sergei a binary to test for windows :)

**Comment by theboy181** [comment]
this is cruel!! link build please..

**Comment by theboy181** [comment]
Culture Brain logo looks a little warped.

**Comment by oddMLan** [comment]
Y'all can check #gliden64 on Discord64 for a build

**Comment by theboy181** [comment]
can someone check FBE in Mario Golf? I think its broken in this build.

**Comment by theboy181** [comment]
image
Is this S2DEX?

**Comment by theboy181** [comment]
Worms does not look like the example above, unless native resolution is used. Is this to be expected?

**Comment by theboy181** [comment]
Here is a bug that can be found in SSB64

2d fix buged

The character transition is broken.

**Comment by theboy181** [comment]
Killer Instinct is another game that suffers.

image

**Comment by gizmo98** [comment]
@theboy181
Thank you! I will check these games later.

**Comment by olivieryuyu** [comment]
those games does not use S2DEX... 

weird

Tested bomberman 2, not sure if it is S2DEX related:

arf

Starcraft and Susume! Taisen Puzzle Dama - Toukon! Marutama Chou have their bugs quenched :)

**Comment by theboy181** [comment]
beettle adventure racing text is bugged.

image

**Comment by olivieryuyu** [comment]
@theboy181 all those bugs are due to native tex recs option.

sans titre

**Comment by olivieryuyu** [comment]
megaman64 have square in intro, except in native res

**Comment by gizmo98** [comment]
@olivieryuyu 
Thank you for finding this out. I have disabled native tex recs and CorrectTexrectCoords.
KI looks good
killer_instinct_gold-002
SSB transition is there
smash_brothers-006
smash_brothers-007
smash_brothers-008
smash_brothers-009

Scaling of everything nativeRes !=1 looks a little bit strange. Just compare nativeRes == 1 with nativeRes == 0. 1 looks smooth, 0 looks pixelated:
f-zero_x_climax-001
f-zero_x_climax-007
f-zero_x_climax-003
f-zero_x_climax-008

**Comment by gizmo98** [comment]
@olivieryuyu 
Don't know why most things look "not so good" if nativeRes != 1. Scaling artifacts of some sort?

**Comment by olivieryuyu** [comment]
I dunno I am afraid :(

**Comment by olivieryuyu** [comment]
@gizmo98 

actually i have an idea about worms and others:

what about

imageFmt;	/* format of texel - G_IM_FMT_* */
imageSiz;	/* size of texel - G_IM_SIZ_*   */

there is a format and size of the texel. I guess that Object Render Mode can be different on its effect according to the size/format of the texel, no?

**Comment by gizmo98** [comment]
@olivieryuyu 
Image format and how many bits per texel:
https://github.com/gonetz/GLideN64/blob/master/src/GBI.h#L224
I think one texel is always one unit in BG image space. Object render mode could be different in it's effect. I don't hope so because it will be really difficult if every constellation differs.

**Comment by gizmo98** [comment]
@olivieryuyu 
Bomberman looks wrong even if i revert all ObjCoordinate changes from the last month.
bomberman64u2-001

I have found another game which looks better. Trees and pathway in Yoshi's Story look better with test branch.
Without changes:
yoshi_story-002
With test branch:
yoshi_story-004

**Comment by olivieryuyu** [comment]
checking again the ucode, something is super odd with imageFmt; /* format of texel - G_IM_FMT_* /
imageSiz; / size of texel - G_IM_SIZ_* */

**Comment by theboy181** [comment]
Glad to hear it’s not a regression. Can I get an updated build?

**Comment by olivieryuyu** [comment]
@theboy181 

it is a general regression but not linked to S2DEX. See https://github.com/gonetz/GLideN64/issues/1889

**Comment by fzurita** [comment]
Here is a zilmar 32 bit build: https://drive.google.com/file/d/1InIAWLCfouEeqmwXpFTIhajBX6tXRj-E/view?usp=sharing

**Comment by gonetz** [comment]
> Scaling of everything nativeRes !=1 looks a little bit strange. Just compare nativeRes == 1 with nativeRes == 0. 1 looks smooth, 0 looks pixelated:

I guess it is because the image in native res is scaled up to screen resolution with bilinear filtering. When native resolution is off, image is rendered in screen resolution without filtering.

**Comment by gonetz** [comment]
@gizmo98 olivieryuyu decoded formulas, which S2DEX uses to calculate vertex coordinates for S2DEX_OBJ_SPRITE command. I replaced current implementation of gSPObjSprite with new one, which uses fixed point arithmetic. The code is in 2D_fixes branch:
https://github.com/gonetz/GLideN64/tree/2D_fixes
New code makes useless my fix 43e0ad500, so it is reverted.
Your fix for sprite's texture coordinates is included.
Please take a look. Since my changes intersect with yours, there will be conflicts to resolve.

Test build:
https://drive.google.com/file/d/1bCVAlu2zMloUt1nTphY4osEcpFHZqk9o/view?usp=sharing

**Comment by gizmo98** [comment]
@gonetz this looks awesone! Nice job :+1: . I will check Yoshi's Story later. 

This is a S2DEX_OBJ_SPRITE fix. Could it fix other Sprite issues as well? 

Just for testing you could rewrite gSPObjSprite like this....
https://github.com/gonetz/GLideN64/blob/master/src/gSP.cpp#L2410
```
const u32 address = RSP_SegmentToPhysical( _sp );
uObjSprite *objSprite = (uObjSprite*)&RDRAM[address];
gSPSetSpriteTile(objSprite);
ObjCoordinates objCoords(objSprite, false);

objCoords.ulx
objCoords.uly
objCoords.lrx
objCoords.lry
objCoords.uls
objCoords.ult
objCoords.lrs
objCoords.lrt
```
...and add the new coord calculation here:
https://github.com/gonetz/GLideN64/blob/master/src/gSP.cpp#L2018

**Comment by olivieryuyu** [comment]
@gonetz i cannot see in your 2dfixes branches the new implemenation of gizmo98 at:

https://github.com/gonetz/GLideN64/compare/master...gizmo98:zelda-fix2?expand=1

@gizmo98 

May be you could propose a PR? :)

**Comment by gonetz** [comment]
@gizmo98 
> This is a S2DEX_OBJ_SPRITE fix. Could it fix other Sprite issues as well?

Sprite command should work properly for all games. Not so many games use it. It works for Parlor and Yoshi.

ObjCoordinates is for Rect commands. Sprite command translated into call of LLE triangle. Rect commands most likely translated into call of TexRect. I don't know, which corrections the microcode does for coordinates in case of Rects. olivieryuyu not decoded that part yet. I can apply the same corrections for Rects too just for testing, yes. May be tomorrow.

> i cannot see in your 2dfixes branches the new implemenation of gizmo98

Yes, Stefan's fixes not included yet. @gizmo98 please rebase your fixes on top of 2D_fixes and make a PR.

**Comment by theboy181** [comment]
@gonetz your download has issues in SD  Hiryuu noKen Densetsu (J)

**Comment by theboy181** [comment]
Super Smash Bros still has the issue I linked above with @gonetz, and @fzurita current test builds too.

**Comment by olivieryuyu** [comment]
@theboy181 

G_BG_COPY is used for SD Hiryuu noKen Densetsu.

it is fixed by gizmo98 implementation which is not yet merged with gonetz branch.

**Comment by olivieryuyu** [comment]
@theboy181 

Super Smash Bros is due to native tex recs option. Many games get broken with it currently. Seems the recent optimization for tex recs creates many issues. Super Smash Bros does not use S2DEX.

**Comment by theboy181** [comment]
@olivieryuyu thanks, makes sense. I guess @gonetz is asking him to use that branch for a PR. Super Smash still has the issue reported with both builds, Is this an issue with something else then ?

**Comment by gizmo98** [comment]
@gonetz 
Your branch works really fine. It also works quite nice with my branch. If both fixes are active Bakuretsu Muteki Bangaioh looks completely fine. There was most of the time one transparent line under buildings and the player and there was one pixel line at the bottom of the text missing.

My branch vs 2D fixes combined:
bangaioh-004
bangaioh-016
 
Yoshi's story's petals are also fixed.

**Pull request merged**
