### PR TITLE
Add Raspberry Pi support

### PR DESCRIPTION
**Pull request by gizmo98**
Add support for raspberry pi's broadcom videocore IV (VC) gpu and raspbian linux distribution.

### CODE REVIEW

**Comment by AmbientMalice** [comment]
Without FB emulation, the list of games that will work grows significantly shorter -- although that's likely just the reality for Pi hardware.

**Comment by gizmo98** [comment]
According to ticket #604 rpi does not support depth texture attachements. So rpi cannot use FB emulation atm.

Even without FB emulatin GLideN64 seems to be more compatible as any other plugin on the pi.

**Comment by AmbientMalice** [comment]
I thought depth texture attachments only affected depth buffer emulation.

**Comment by gizmo98** [comment]
I don't know. According to the above mentioned ticket depth buffer texture attachements seem to be necessary. If FB emulation is on screen stays black.

**Comment by gonetz** [comment]
Yes, Frame Buffer Object needs both color and depth attachments. You will not get depth buffer functionality without depth attachment.

**Comment by gizmo98** [comment]
#gonetz 
Thank you! I will modify unsigned, location of getDisplaySize and m_bFullscreen check. Do you have any other suggestions?
GCC-4.7 is not working. You use std::map::emplace http://en.cppreference.com/w/cpp/container/map/emplace. There is a "function emplace not found" error. You need at least GCC-4.8 to use this function. The current GNU compiler check does not work.

**Comment by gizmo98** [comment]
Ok. I modified the mentioned code and recompiled everything. It still runs.

**Comment by gonetz** [comment]
Good. I have added few requests to code appearance.
Plus, now your changes conflict with current master. I just merged bunch of modifications to it, including config files.
Please fix the conflicts. Also, please combine "Add gcc version check" and "cmake: merge gcc checks" into one commit. Same for "rpi: use screen resolution if fullscreen=1" and "rpi: move platform specific code into own function ".

**Comment by gizmo98** [comment]
@gonetz 
I have added all changes to your last commit. https://github.com/gizmo98/GLideN64/commits/rpi-fix

There is a "undefined symbol: osal_is_directory" error now. I have seen you modified osal library position lately:
https://github.com/gonetz/GLideN64/commit/f212710ea752bc473566c493a8530f02d9b82827

**Comment by gizmo98** [comment]
I fixed the "undefined symbol: osal_is_directory"  bug.

**Comment by dankcushions** [comment]
In mupen64plus, the screenwidth/height config options are commented as being for windowed resolutions AND full screen resolutions. I tried using those for a pi3 (by adjusting https://github.com/gonetz/GLideN64/pull/750/commits/e1cb0fa4f576bb8e74e151c44b1641fbffe0455c to pick up the config height/width, rather than the current screen resolution), but it would mean there was only a small image displayed in the corner.

Is this just the way GLideN64 works for all hardware? It always want to use the current screen resolution, rather than the configured one?

**Comment by gizmo98** [comment]
If fullscreen is enabled it uses your screen resolution if you have a raspberry pi. If you have a PC screen resolution will be switched to screenwidth/height config. Mupen64plus uses SDL2. As far as i know SDL2 does not support screen resolution switching on a pi.

**Pull request closed without merging**
