### PR TITLE
Fix flickering when rdram to color buffer is enabled

### PR DESCRIPTION
**Pull request by fzurita**
I think clearing RDRAM only makes sense if we are not copying color buffer to RDRAM ourselves.

Without this, if copy color to RDRAM happens at 60 VI/s and copy color buffer to RDRAM happens at a lower rate, we get flickering in the screen. For example Mario Artist - Paint Studio.

### CODE REVIEW

**Comment by loganmc10** [comment]
This mostly fixes the flickering in Pokemon Snap when EnableCopyColorFromRDRAM is enabled (so the red dot works), however the borders of the image still flicker when you "target" with Z. Without this change the whole image is constantly flickering if EnableCopyColorFromRDRAM is on

**Comment by fzurita** [comment]
Ok, I can take a look at that tomorrow.

**Comment by AmbientMalice** [comment]
I believe the Wii VC version of this game uses a hack where only the buffer area inside the borders is copied. Regardless, this is a great find and hopefully it helps in other areas, too.

**Comment by fzurita** [comment]
I think I see why the flickering at the borders of the screen when taking a picture is happening. I"ll have to think of a way to fix it.

**Comment by gonetz** [comment]
Merged: 77a777162cff5
Thanks!

**Pull request closed without merging**
