### PR TITLE
GLideNHQ subproject: Do not attempt to bring in OpenGL

### PR DESCRIPTION
**Pull request by Nebuleon**
I attach a commit that leaves the task of finding OpenGL or OpenGL ES to the main project, GLideN64, controlled by the `GLES2` variable in CMake. Whatever it uses is also used by GLideNHQ.

This is intended to be a fix for issue #810.

### CODE REVIEW

**Comment by vgturtle127** [comment]
The other issue was closed, so is this fixed in the main repository, or does this need to be merged/investigated?

**Comment by Nebuleon** [comment]
I closed the issue because it's now being tracked in this pull request, which still needs to be merged.

If this repository's issues and pull requests don't work that way, I'm sorry. I just learned it like that in other repositories. :)

**Comment by vgturtle127** [comment]
@Nebuleon OK, just making sure. I never really learn since it changes day to day with most repositories. :stuck_out_tongue_closed_eyes:

**Comment by gonetz** [comment]
I rebuilt the project with updated cmake files on my Linux VM. Nothing is broken :) I hope that #810 is fixed also.

**Pull request merged**
