### PR TITLE
Add bilinear filtering modes which remove halos around transparent te…

### PR DESCRIPTION
**Pull request by gizmo98**
…xtures.

0=N64 3point, 1=standard, 2=N64 3point with color bleeding, 3=standard with color bleeding and premultiplied alpha.

New options fix halos around transparent textures in pokemon puzzle league, mario kart, body harvest, puyo pyuo etc.

New bilerp options are not implemented for gles2 devices.
https://github.com/gonetz/GLideN64/issues/1933

### CODE REVIEW

**Comment by tony971** [comment]
Since the optimal setting is game dependent, is this something that could possibly make its way to the gliden64.custom.ini?

**Comment by gonetz** [comment]
Merged, thanks!

**Comment by gonetz** [comment]
> Since the optimal setting is game dependent, is this something that could possibly make its way to the gliden64.custom.ini?

Yes. It is usual config setting. Just add
`texture\bilinearMode=2`
or
`texture\bilinearMode=3`
to custom section of your game.

**Comment by tony971** [comment]
Sorry, I wasn't very specific. What I meant was having an "auto" option and the best setting for each game loaded into the default custom.ini

**Comment by gonetz** [comment]
"best setting" is individual imo.
Some people prefer PC-style filtering, others like N64-style more.
I think, it will be better to add an option "remove halos", which will enable fixed bilinear filtering for user-selected filtering style. In that case it will be possible to enable that option in custom.ini for all games, which suffer from "halos" issue.

**Pull request closed without merging**
