### PR TITLE
Correct mip-map shader for the case when texture level is 0 and detai…

### PR DESCRIPTION
**Pull request by gonetz**
…led texture enabled

### CODE REVIEW

**Comment by gonetz** [comment]
@standard-two-simplex please check.

**Comment by standard-two-simplex** [comment]
It seems it is working fine.

**Comment by gonetz** [comment]
> What was the reason for this? I believe uMaxTile should be gSP.texture.level always.

I agree. It is probably a rudiment from the older mipmap implementation.

**Comment by gonetz** [comment]
Fix updated. Previous variant caused issues with Zelda MM HD pack.

**Pull request merged**
