### PR TITLE
Ini Cleanup.

### PR DESCRIPTION
**Pull request by AmbientMalice**
Removed redundant async entries. (Async is default. Forcing it is counterproductive. It should only be forced to sync and OFF when needed,) Disabled depth buffer for Shadow Man, since that breaks pause menu.

### CODE REVIEW

**Comment by loganmc10** [comment]
For some reason this is showing up as a binary file on GitHub, the diff isn't working.

**Comment by AmbientMalice** [comment]
@loganmc10 I noticed that. Maybe there's something wrong with the web editor?

**Comment by loganmc10** [comment]
I'm not sure, the pull request I just sent was edited on GitHub

**Comment by AmbientMalice** [comment]
I'll try again.

**Pull request closed without merging**
