### PR TITLE
Fixed crop image W: label not disabling

### PR DESCRIPTION
**Pull request by Aquatakat**
I tried my hand at fixing ConfigDialog.cpp for the initial display but there seems to be something wrong with lines 84 and 86 that I couldn't figure out.

### CODE REVIEW

**Comment by gonetz** [comment]
Issues:

* Crop image spinbox enable/disable works incorrect after fn emulation toggled. I'll try to fix it in code.
* OSD preview label not changed after new color/font selected. Font label is changed instead, as before. Probably, code support is needed.

**Comment by Aquatakat** [comment]
The behaviour for the OSD preview label could possibly be how I intended (I can't compile so I haven't tested):

Font: [Font - Size] [Select]
Color: #hex [Pick]

[Preview]

With the preview displaying "Preview" but showing the correct background and foreground colour.

**Comment by Aquatakat** [comment]
First issue I don't know how to fix - mostly because the init value is currently incorrect.

The second issue I'll commit in a moment.

**Comment by gonetz** [comment]
I fixed both issues

**Comment by Aquatakat** [comment]
Good.

**Pull request closed without merging**
