### PR TITLE
A possible fix for disabled/enabled controls

### PR DESCRIPTION
**Pull request by Aquatakat**
This fix is a bit dumb but I have a feeling it might work. There's probably a better way of doing this.

### CODE REVIEW

**Comment by gonetz** [comment]
Are you trying to send "toggle"signal that way? I'm sure there should be another way.

**Comment by Aquatakat** [comment]
I'm sure there's another way too, but I don't know what it is.

**Comment by gonetz** [comment]
Why you don't want to put texture pack settings to checkable group box? If you don't like borders, it can be made with no border:
http://www.qtforum.org/article/27045/remove-border-qgroupbox.html

**Comment by Aquatakat** [comment]
The borders add unnecessary visual complexity.

When the borders are removed, it doesn't appear that you can adjust the position of the group box's checkbox:

image

**Comment by Aquatakat** [comment]
Given the way UIs are designed I'm sure there's some kind of method like `Qt::processAllSignals` or something like that. It's weird that I haven't been able to find it yet.

**Comment by gonetz** [comment]
Ok, another way is to call toggle before setChecked:
```
    ui->texturePackOnCheckBox->toggle();
    ui->texturePackOnCheckBox->setChecked(config.textureFilter.txHiresEnable != 0);

```
It is slightly better than two setChecked, and it works.

**Comment by Aquatakat** [comment]
I've been looking and couldn't find a clean solution. I'll submit new code using `->toggle()`

**Comment by gonetz** [comment]
Ok.

**Comment by Aquatakat** [comment]
It really is weird that whatever object the `ui` variable is doesn't seem to have at Qt method of processing all of the signals before displaying the output.

**Comment by gonetz** [comment]
Ok, it works. Thanks!
Now need to polish options names and tooltips.

Also, let's try to implement oddMLan suggestion:
https://github.com/gonetz/GLideN64/issues/1213#issuecomment-259053325
I'll put it to alternative branch, and give users to compare.

**Pull request merged**
