### PR TITLE
Fix valgrind issues

### PR DESCRIPTION
**Pull request by fzurita**
Fixes https://github.com/gonetz/GLideN64/issues/1626

Valgrind comes out clean after these changes.

One thing I'm not quite sure about is the default ```size``` attribute for frame buffer textures. ```glsl::UFrameBufferInfo::update``` depends on the size attribute to be set to something, but at startup we are calling this before the size attribute is ever being set. I defaulted it to 2 for now.

### CODE REVIEW

**Comment by fzurita** [comment]
This seems to fix https://github.com/gonetz/GLideN64/issues/1582 without having to rely on an entry for GLideN64.custom.ini to set ```copyDepthToRDRAM=0```.

**Comment by gonetz** [comment]
Thanks!

**Comment by fzurita** [comment]
@gonetz Thanks for closing this so quickly, but did you see my question about the initial size parameter value?

**Comment by gonetz** [comment]
> did you see my question about the initial size parameter value?

I did not notice it, sorry.

> I guess it doesn't matter, as long as it prevents the monochrome modes or fixed alpha from being updated on textures that don't need it.

You should be right.

**Pull request merged**
