### PR TITLE
German translation part 2

### PR DESCRIPTION
**Pull request by gizmo98**

### CODE REVIEW

**Comment by gonetz** [comment]
@gizmo98 
I merged the translation without check. It actually does not work. There are plenty of such errors:
lrelease error: Parse error at gliden64_de.ts:186:235: Entity 'auml' not declared.
lrelease error: Parse error at gliden64_de.ts:317:113: Entity 'uuml' not declared.
lrelease error: Parse error at gliden64_de.ts:317:128: Entity 'ouml' not declared.

xml can't take strings like this "Aufl&ouml" "Fensterr&auml"

**Comment by gizmo98** [comment]
Ok. Sorry. I will replace them.

**Comment by gizmo98** [comment]
I thought this would be the right way to write ä, ö and ü in html.

**Comment by gizmo98** [comment]
xml is different:
http://www.devtrain.de/artikel_296.aspx
&auml; --> &#228;
&uuml; --> &#246;
&ouml; --> &#246;

**Pull request merged**
