### PR TITLE
Apply Quake II hack to Quake 64.

### PR DESCRIPTION
**Pull request by AmbientMalice**
I have no idea whether I got the syntax right thanks to not being able to build GLideN64. Assuming this works, this should fix underwater rendering in Quake 64.

### CODE REVIEW

**Comment by olivieryuyu** [comment]
i don't think we should go to too much hacks

**Comment by AmbientMalice** [comment]
GLideN64 used to perform the necessary buffer swap check on all games, but it was causing rare performance issues so it was made a game specific hack - https://github.com/gonetz/GLideN64/commit/16e3af616c52db22638cacef60eb7dade73584bc

**Comment by Predator82Germany** [comment]
Can hacks not be written in a special seperated section in the plugin code?

**Comment by olivieryuyu** [comment]
i believe there should be a box in the GUI where we could deactivate ALL hacks. Would be nice

**Comment by Predator82Germany** [comment]
Then a new tab were usefull

**Comment by Predator82Germany** [comment]
Or both :)

**Comment by gonetz** [comment]
https://github.com/gonetz/GLideN64/commit/b8d9d30ecc7f67bec60c43896850ee56a3803296

**Pull request closed without merging**
