### PR TITLE
 Optimize Perfect Dark framebuffer effects 

### PR DESCRIPTION
**Pull request by purplemarshmallow**
Like #704 but this does not break the portraits in Pokemon Stadium 2

### CODE REVIEW

**Comment by baptiste0602** [comment]
Now I can play Perfect Dark at fullspeed in HiRez, thanks !

**Comment by purplemarshmallow** [comment]
:)

**Comment by AmbientMalice** [comment]
Good work.

**Comment by gonetz** [comment]
Added, thanks!
https://github.com/gonetz/GLideN64/commit/f487225b481f1d9119c73dc2c5263cb5a0de0cb8

**Pull request closed without merging**
