### PR TITLE
ci: move to github actions

### LINKED ISSUE #2530: Artifacts older than 1 month are automatically deleted
This means I can't download master builds if the latest commit was done over a month ago.

### LINKED ISSUE #2540: Make GLideNUI builds for mupen64plus on AppVeyor
Currently, mupen64plus builds are CLI only, and the settings dialog won't work on most frontends.

### PR DESCRIPTION
**Pull request by Rosalie241**
I'm not sure if you like the way this packages things but that can be changed.

do note that github actions requires users being logged in to be able to download the artifacts, this can be worked around by allowing github actions to make 1 release where it keeps the artifacts up-to-date, I'll work on that if you want.

Artifacts will be available for 90 days.

Fixes #2540 
Fixes #2530

@oddMLan @Jj0YzL5nvJ please take a look

### CODE REVIEW

**Comment by Rosalie241** [comment]
I'm not sure why github actions isn't running for this PR right now (possibly due to not being included in this repo yet?), however you can check what artifacts there are here:

https://github.com/Rosalie241/GLideN64/actions/

**Comment by Jj0YzL5nvJ** [comment]
My only complaint would be to change `mupen64plus-nogui` to `Mupen64Plus-CLI` and `mupen64plus-GLideNUI` to `Mupen64Plus-Qt`.
I think it would be better not to include the creation of shared modules in the batch script, but I will reflect the changes already mentioned for better clarification.

**Comment by gonetz** [comment]
> I'm not sure why github actions isn't running for this PR right now (possibly due to not being included in this repo yet?), however you can check what artifacts there are here:

Cool! I did not setup Actions for my repo yet. Do I need to do it manually, or adding .github/workflows/build.yml is enough?



> My only complaint would be to change `mupen64plus-nogui` to `Mupen64Plus-CLI` and `mupen64plus-GLideNUI` to `Mupen64Plus-Qt`.

Yes, it looks better.

**Comment by Rosalie241** [comment]
> Cool! I did not setup Actions for my repo yet. Do I need to do it manually, or adding .github/workflows/build.yml from this PR is enough?

Merging this PR should be enough to get it working, though you'll need to de-activate appveyor by going to the project settings there.

> Yes, it looks better.

Sure, I'll get on that then

**Comment by Rosalie241** [comment]
I've added the changes and I've also made it so that the CI will create a release called `github-actions` where it'll put the latest artifacts (from the master branch):

https://github.com/Rosalie241/GLideN64/actions/runs/1179456177
https://github.com/Rosalie241/GLideN64/releases/tag/github-actions

should be ready for merging now I think

**Comment by gonetz** [comment]
> should be ready for merging now I think

The result looks great, thanks!
As I understand, actions make current Continuous Integration (AppVeyor and Travis) useless.
If so, README.md also should be changed, since currently it takes CI results from  AppVeyor and Travis.

**Comment by Rosalie241** [comment]
Updated the README (status icon doesn't appear yet due to not having github actions in this repo yet, it'll appear when merged)

**Review by gonetz — APPROVED** [review]

**Comment by gonetz** [comment]
Thanks!

**Pull request merged**
