### PR TITLE
Fix x64 Zilmar build

### PR DESCRIPTION
**Pull request by tim241**

### CODE REVIEW

**Comment by gonetz** [comment]
@tim241 Do you have static build of QT libs for x64?

**Comment by tim241** [comment]
Yes, do you want me to upload that and add a link to the wiki?

**Comment by gonetz** [comment]
Yes, it would be great. Besides, I can't test your commit without it since I have only win32 libs.

**Comment by tim241** [comment]
I've updated the wiki and added the link

**Comment by gonetz** [comment]
Thanks! I don't have VS 2017 installed, I'll check it tomorrow.

**Comment by tim241** [comment]
I built it with vs2019 but since qt doesn't have that as platform yet, I targeted vs2017 which worked fine.

On November 4, 2019 11:00:46 AM GMT+01:00, Sergey Lipskiy <notifications@github.com> wrote:
>Thanks! I don't have VS 2017 installed, I'll check it tomorrow.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gonetz/GLideN64/pull/2122#issuecomment-549285550

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gonetz** [comment]
I still use VS2015. I tried to use your libs with it. GLideNUI built succesfully, but then I got lots of "unresolved external symbol" errors.
BTW, could you upload x64 build of Project64 as well? I can't find ready build to test.

**Comment by tim241** [comment]
Project64 added appveyor recently, it also builds x64, here's the latest currently:
https://ci.appveyor.com/project/project64/project64/builds/28560903/job/h871x4ed7to44lhn/artifacts

On November 4, 2019 11:48:36 AM GMT+01:00, Sergey Lipskiy <notifications@github.com> wrote:
>I still use VS2015. I tried to use your libs with it. GLideNUI built
>succesfully, but then I got lots of "unresolved external symbol"
>errors.
>BTW, could you upload x64 build of Project64 as well? I can't find
>ready build to test.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gonetz/GLideN64/pull/2122#issuecomment-549301123

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gonetz** [comment]
Cool, thanks!

**Comment by gonetz** [comment]
@tim241 I've tried to make x64 Zilmar build with VS 2017, but got the same bunch of errors, as with VS 2015:

<details><summary>Errors</summary>

```
1>GLideNUI.lib(qlockfile_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qxmlstream.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qabstractanimation.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qlibrary_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qtimezoneprivate_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qurlquery.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qurl.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(quuid.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qstandardpaths_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qitemselectionmodel.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qlocale_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qdatetimeparser.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qtsciicodec.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qfilesystemiterator_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qcoreapplication_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qeventdispatcher_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qsettings.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qlibrary.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qfilesystemengine_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qdatetime.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qfsfileengine_win.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qvariant.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qtextcodec.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qtextstream.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qmetaobject.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qtemporaryfile.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qtranslator.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qglobal.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qlocale.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qregexp.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qbytearray.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qstring.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qfile.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideNUI.lib(qcoreapplication.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4
1>GLideN64\projects\msvc\bin\x64\Release\GLideN64.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "GLideN64.vcxproj" -- FAILED.
```

</details>

I don't have VS 2019.
Could you rebuild QT libs with VS 2017?

**Comment by tim241** [comment]
Done, I've updated the wiki with the vs2017 build.

**Comment by gonetz** [comment]
Your build contains only release libs. Release build linked fine with your libs.
I'll upload complete set, with debug libs.
Also, post-build needs correction: it currently copies result into $(N64PluginsDir) folder, which points to Plugin folder with 32bit plugins. @tim241 could you do it? I tried to edit project's property in VS, but it alters post-build step for x86 configuration too. Env variable for x64 Plugin folder should be $(N64PluginsDir_x64)

**Comment by tim241** [comment]
I totally forgot about the debug libs, will rebuild the vs2019 static qt build!

the post-build correction has been pushed aswell 👍

**Comment by gonetz** [comment]
@tim241 Thanks! Merged: 97d3e2f87c

**Pull request closed without merging**
