### PR TITLE
Remove Android makefiles and use CMakeLists for Android instead

### PR DESCRIPTION
**Pull request by fzurita**
As the title says. Android will now use the same CMakeLists file as for unix builds instead of Android specific makefiles.

### CODE REVIEW

**Comment by fzurita** [comment]
I have no good way of verifying that I didn't break anything in other platforms that depend on the CMakeLists file.

What happened to the automated builds?

**Comment by oddMLan** [comment]
fzurita force pushed changes to this branch

**Comment by fzurita** [comment]
Yep, I added automatic generation of Revision.h

**Comment by gonetz** [comment]
Mac build failed

/Users/travis/build/gonetz/GLideN64/src/TextDrawer.cpp:13:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.

**Comment by fzurita** [comment]
Hmmm, freetype issues, maybe one of my conditionals wasn't right

**Comment by fzurita** [comment]
I found the problem, this should be ```else``` not ```elseif```:
https://github.com/gonetz/GLideN64/commit/d69b794c0a27b3bbc9fce58fe23ae8b44df1c800#diff-95e351a3805a1dafa85bf20b81d086e6R324

**Comment by gonetz** [comment]
Yes, I found it too :)
I force updated the commit.

**Comment by fzurita** [comment]
Ok, great, thanks!

**Comment by fzurita** [comment]
Potentially, you could do even more consolidation:

https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019

Visual studio can also use CMake as well it seems.

**Comment by gonetz** [comment]
May be someday. Current VS projects are good.

**Pull request merged**
