### PR TITLE
Ptit seb master

### PR DESCRIPTION
**Pull request by ptitSeb**

### CODE REVIEW

**Comment by ptitSeb** [comment]
Useless :( it's the same pull request

**Comment by ptitSeb** [comment]
At last, it seems good this time.

**Comment by gonetz** [comment]
Nope, no good:
-	const double ref_X =  95.047;        //Observer= 2°, Illuminant= D65
+	const double ref_X =  95.047;        //Observer= 2?, Illuminant= D65
redundant change. You removed unicode symbol just for nothing.You had to left that file untouched in the first commit.

**Comment by gonetz** [comment]
Also, in Config.cpp:
+	#ifdef PANDORA
#ifdef should be without any indent before it.
Please fix. I'll check that your changes do not break other platforms.

**Comment by ptitSeb** [comment]
Done.

**Comment by gonetz** [comment]
Thanks! Pushed.

**Pull request merged**
