### PR TITLE
Added an option to force gamma correction level

### PR DESCRIPTION
**Pull request by Gillou68310**

### CODE REVIEW

**Comment by AmbientMalice** [comment]
Is this going to be added to the Zilmar version down the track? If so, where would gamma override be located?

**Comment by gonetz** [comment]
>Is this going to be added to the Zilmar version down the track?

I doubt that it is necessary. If somebody will find it useful, it can be added to GUI also.

**Comment by Gillou68310** [comment]
I thinks @gonetz is right this option has been initialy added to fix a limitation on android where you can't change gamma level via the OS.

**Comment by gonetz** [comment]
Looks good. Merged. Thanks!

**Pull request merged**
