### PR TITLE
Update gliden64_fr.ts

### PR DESCRIPTION
**Pull request by BenjaminSiskoo**

### CODE REVIEW

**Comment by gonetz** [comment]
Thanks for the update!

I have a question: do you use Qt Linguist for editing translation file, or you corrected it in a text editor?
I ask it because I see <translation type="unfinished"> in translation file. I expected such tags removed after translation.

**Comment by BenjaminSiskoo** [comment]
thanks to you.

Never heard about Qt Linguist ^^

Here the steps : 
- https://github.com/gonetz/GLideN64/pull/872#issuecomment-188341284
- I clicked on the pen - Edit the file in your fork of this project.
- And propose file change.

I would like to improve this translation. Any news from the former french translator ?

Keep up the good work

**Comment by baptiste0602** [comment]
Hello @BenjaminSiskoo,

I'm the former french translator. What do you want to know ?
You can find some info in wiki : https://github.com/gonetz/GLideN64/wiki/Internationalization

Feel free to improve the translation, you have a better experience than me :)
And I can help you

**Comment by BenjaminSiskoo** [comment]
Salut Baptiste,

Je vais apporter des modifications, ajouts, corrections. Tu as fait un très bon travail. Hésite pas à vérifier ce que je vais mettre en ligne, tu peux aussi avoir une meilleur traduction.

En tout les cas très sympa :)

**Pull request merged**
