### PR TITLE
UI: N64 depth compare disables anti-aliasing

### PR DESCRIPTION
**Pull request by Aquatakat**

### CODE REVIEW

**Comment by gonetz** [comment]
Labels look wrong now:
gui

**Comment by gonetz** [comment]
Hmm, master looks the same.

**Comment by gonetz** [comment]
It was broken in master after Release 2.0

**Comment by Aquatakat** [comment]
I re-added the spacer size hint XML. I guess it's one of those things that behaves differently in the preview vs. compiled.

**Comment by gonetz** [comment]
Fixed. Thanks!

**Pull request merged**
