### PR TITLE
Fix S2DEX one-piece backgrounds

### PR DESCRIPTION
**Pull request by standard-two-simplex**
Should be tested first

### CODE REVIEW

**Comment by gonetz** [comment]
I'm testing it now.

**Comment by standard-two-simplex** [comment]
It still has the issues discussed in #2484. I remember trying to apply a texture coordinate offset, in a similar way to texture rectangles, but there was still an issue with the last line, so I wasn't satisfied.

I will upload the test tomorrow for reference.

**Comment by gonetz** [comment]
The fix works, but "one-piece backgrounds" are incompatible with "native-res texrects" - heavy glitches when both options are enabled.

> It still has the issues discussed in #2484. 

Yes, it has :(

**Comment by standard-two-simplex** [comment]
The last commit adjusts the one piece background behaviour with regarding the texture coordinte offset to that of texture rectangles.

There is still the issue of the last line in higher resolutions. This type of issue seems to be common to many games. When rendering in non-native, bigger texture coordinates are reached. This causes fetching outside the intended texture.

In my opinion, the best possible solution is using texture coordinate bounds, as with texture rectangles. I believe it should be possible to compute good bounds. However, the current implementation seems to be failing in some aspects.

I tried computing bounds for one-piece backgrounds too. I had trouble with finding good bounds. It seems that the texture coordinates computed by GLideN64 are offset (not sure why), so the clamping bound fails. This causes issues like #2304 when I try to clamp the texture coordinates.

**Comment by gonetz** [comment]
I'd like to actualize that fix. Current issue: regression in native res mode.

**Comment by gonetz** [comment]
I see that your commit https://github.com/standard-two-simplex/GLideN64/commit/51b9a3449175143a8b940cad42ceecc40ba7328c
is not included into this PR. Is it on purpose?

**Comment by standard-two-simplex** [comment]
> Is it on purpose?

Yes, it is unfinished. I wanted to use the boolean for validity instead of forcing the bounds for background textures.

This PR fixes the blur, which is the regression. The other commits try to address the extra lines at the bottom. I will try to finish it with the hint you left on the issue thread.

**Comment by standard-two-simplex** [comment]
I realize now that these commits were merged. I will close the PR, but leave the issue open until the discussion there is resolved.

**Pull request closed without merging**
