### PR TITLE
Fix performance issues on AMD+Mesa GPUs

### PR DESCRIPTION
**Pull request by loganmc10**
@Jj0YzL5nvJ can you please test this and let me know if it resolves all your issues? I'm hoping this also resolves ```EnableCopyColorToRDRAM=2``` for you, so please try that out as well.

Should fix https://github.com/gonetz/GLideN64/issues/1561

### CODE REVIEW

**Comment by loganmc10** [comment]
Here is the comment on the Mesa bug tracker that helped me resolve this issue: https://bugs.freedesktop.org/show_bug.cgi?id=105256#c1

**Comment by loganmc10** [comment]
By the way, I didn't make the GL_UNSIGNED_SHORT thing GPU specific because the person on the bug tracker indicated (https://bugs.freedesktop.org/show_bug.cgi?id=105256#c4) that this doesn't just apply to AMD GPU's but there are a few older Nvidia GPU's as well.

Without a perfect list of all the GPU's that this might affect, I think the larger element size is an OK price to pay to fix compatibility on those cards.

**Comment by fzurita** [comment]
I tested this on a low end Adreno device and saw no difference in performance.

**Comment by Jj0YzL5nvJ** [comment]
In my case this change is a partial fix https://github.com/gonetz/GLideN64/issues/1561#issuecomment-368838242

**Comment by loganmc10** [comment]
@Jj0YzL5nvJ Is it full speed when you have ```EnableCopyColorToRDRAM=0```?

**Comment by loganmc10** [comment]
I added a commit to using client side data for the elements. This is how Dolphin does it and I assume they've done more testing than us.

@Jj0YzL5nvJ I just need to know if change fixes the speed with ```EnableCopyColorToRDRAM=0```, then we know that you just have an issue left with EnableCopyColorToRDRAM or not

**Comment by gonetz** [comment]
The first commit is ok, if it really fixes performance issues on AMD+Mesa GPUs, does it?

But the second one is questionable. It is not the reason to switch to client side data for the elements just because Dolphin does that. It can be caused by specific of Dolphin data flow, and thus has no benefits for us. My point: lets not touch it if it does not bring any performance improvements.

**Comment by loganmc10** [comment]
I'm just waiting to hear back from @Jj0YzL5nvJ , another ATI user reported that it fixed the issue, but @Jj0YzL5nvJ also has issues with EnableCopyColorToRDRAM, so I am just trying to seperate the issues.

As far as the element buffer, it was actually changed during the graphics refactoring, before that it was client side data. @fzurita reported that the switch to VBO/EBO was actually a slight performance hit on Android (https://github.com/gonetz/GLideN64/issues/1561#issuecomment-368550340). I believe buffer objects are only really a benefit if you can reuse the data, since you can just reference the data in the buffer without uploading. But when the data changes every time, I don't think there is any benefit to buffer objects.

The unbuffered drawer is probably the same or faster than buffered drawer, but we have to use VBOs because it's mandated by OpenGL core profile. It isn't mandated for element arrays

**Comment by BPaden** [comment]
@gonetz 

The effects of the ushort patch on early GCN cards and below are pretty dramatic. From ~10-15 FPS reported by Mesa on my machine to ~60.

> But the second one is questionable. It is not the reason to switch to client side data for the elements just because Dolphin does that. It can be caused by specific of Dolphin data flow, and thus has no benefits for us. My point: lets not touch it if it does not bring any performance improvements.

The buffer patch alone does improve the FPS reported by Mesa by about ~5-10.

**Comment by Jj0YzL5nvJ** [comment]
> @Jj0YzL5nvJ Is it full speed when you have EnableCopyColorToRDRAM=0?

loganmc10/GLideN64@9bcfa67
loganmc10/GLideN64@6527537
loganmc10/GLideN64@fa0ab9d

All three give the same results with `EnableCopyColorToRDRAM=0`, because of that I omitted their results.
The best results be achieved with loganmc10/GLideN64@29dc6a1

Even adapt the code on loganmc10/GLideN64@9bcfa67 and loganmc10/GLideN64@6527537 in two new variants of loganmc10/GLideN64@29dc6a1. But both were inferior to loganmc10/GLideN64@29dc6a1 alone.

**Comment by loganmc10** [comment]
I guess I'm getting a little confused, if you set ```EnableCopyColorToRDRAM=0``` and use the commits in this PR, do you get food performance? Is it better than the current master? We can sort about EnableCopyColorToRDRAM later

**Comment by Jj0YzL5nvJ** [comment]
I don't want to offend, but any of your hotfixes is better that 'master'...
I leave you my last benchmark here https://github.com/gonetz/GLideN64/issues/1561#issuecomment-369155714

**Comment by gonetz** [comment]
> The unbuffered drawer is probably the same or faster than buffered drawer, but we have to use VBOs because it's mandated by OpenGL core profile. It isn't mandated for element arrays

Ok, you convinced me.

> The buffer patch alone does improve the FPS reported by Mesa by about ~5-10.

Hard to believe, but I have no Mesa powered devices to test.

**Comment by loganmc10** [comment]
Just the buffer thing caused the issue right? Changing the elements to a short is ok? That was what actually fixed the performance so that's ok

**Comment by gonetz** [comment]
Yes, changing the elements to a short is ok

**Comment by gonetz** [comment]
I put ebo commit to remove_ebo branch, in case somebody want to sort out, what is going on there.

**Pull request merged**
